/**
 * Dados fictícios de demonstração. Nenhum número de cartão, CPF ou CEP
 * listado aqui pertence a uma pessoa real.
 */
import type { Cliente } from '../types/cliente';

export const mockClientes: Cliente[] = [
  {
    id: 'c1-abc-123',
    nome: 'Ana Clara de Albuquerque Cavalcanti do Nascimento Silva',
    email: 'ana.clara.albuquerque.cavalcanti@correiodomomento.com.br',
    genero: 'Feminino',
    telefone: { tipo: 'Celular', ddd: '11', numero: '98765-4321' },
    cpf: '123.456.789-01',
    dataNascimento: '1991-03-14',
    ranking: 5,
    isAtivo: true,
    enderecos: [
      {
        id: 'end-c1-1',
        nome: 'Casa',
        tipo: 'ambos',
        tipoResidencia: 'Apartamento',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua dos Pinheiros',
        numero: '482',
        bairro: 'Pinheiros',
        cep: '05422-030',
        cidade: 'São Paulo',
        estado: 'SP',
        pais: 'Brasil',
        observacoes: 'Portão azul, tocar o interfone 42.',
      },
      {
        id: 'end-c1-2',
        nome: 'Trabalho',
        tipo: 'entrega',
        tipoResidencia: 'Comercial',
        tipoLogradouro: 'Avenida',
        logradouro: 'Avenida Brigadeiro Faria Lima',
        numero: '1811',
        bairro: 'Itaim Bibi',
        cep: '04538-133',
        cidade: 'São Paulo',
        estado: 'SP',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [
      {
        id: 'car-c1-1',
        numero: '4539 7812 3456 1002',
        nomeImpresso: 'ANA CLARA A C NASCIMENTO SILVA',
        bandeira: 'Visa',
        codigoSeguranca: '123',
        isPreferencial: true,
      },
      {
        id: 'car-c1-2',
        numero: '5412 7534 8821 4470',
        nomeImpresso: 'ANA CLARA A C N SILVA',
        bandeira: 'Mastercard',
        codigoSeguranca: '456',
        isPreferencial: false,
      },
      {
        id: 'car-c1-3',
        numero: '6362 9710 4453 2298',
        nomeImpresso: 'ANA CLARA SILVA',
        bandeira: 'Elo',
        codigoSeguranca: '789',
        isPreferencial: false,
      },
    ],
  },
  {
    id: 'c2-def-456',
    nome: 'Carlos Eduardo Oliveira',
    email: 'kadu.oliveira@gmail.com',
    genero: 'Masculino',
    telefone: { tipo: 'Celular', ddd: '21', numero: '99988-7766' },
    cpf: '234.567.890-12',
    dataNascimento: '1985-11-02',
    ranking: 3,
    isAtivo: true,
    enderecos: [
      {
        id: 'end-c2-1',
        nome: 'Casa',
        tipo: 'ambos',
        tipoResidencia: 'Apartamento',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Barata Ribeiro',
        numero: '540',
        bairro: 'Copacabana',
        cep: '22051-000',
        cidade: 'Rio de Janeiro',
        estado: 'RJ',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [
      {
        id: 'car-c2-1',
        numero: '5589 3312 7765 0041',
        nomeImpresso: 'CARLOS E OLIVEIRA',
        bandeira: 'Mastercard',
        codigoSeguranca: '321',
        isPreferencial: true,
      },
      {
        id: 'car-c2-2',
        numero: '3717 445982 10093',
        nomeImpresso: 'CARLOS EDUARDO OLIVEIRA',
        bandeira: 'American Express',
        codigoSeguranca: '1234',
        isPreferencial: false,
      },
    ],
  },
  {
    id: 'c3-ghi-789',
    nome: 'Juliana Mendes',
    email: 'ju.mendes88@outlook.com',
    genero: 'Feminino',
    telefone: { tipo: 'Residencial', ddd: '31', numero: '99123-0000' },
    cpf: '345.678.901-23',
    dataNascimento: '1988-07-23',
    ranking: 1,
    isAtivo: false,
    enderecos: [
      {
        id: 'end-c3-1',
        nome: 'Apartamento',
        tipo: 'ambos',
        tipoResidencia: 'Apartamento',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Pium-í',
        numero: '210',
        bairro: 'Savassi',
        cep: '30140-070',
        cidade: 'Belo Horizonte',
        estado: 'MG',
        pais: 'Brasil',
        observacoes: 'Interfone 12, apto 302.',
      },
      {
        id: 'end-c3-2',
        nome: 'Casa da minha mãe',
        tipo: 'entrega',
        tipoResidencia: 'Casa',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Guajajaras',
        numero: '88',
        bairro: 'Centro',
        cep: '30180-100',
        cidade: 'Belo Horizonte',
        estado: 'MG',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [
      {
        id: 'car-c3-1',
        numero: '6362 1198 4432 0087',
        nomeImpresso: 'JULIANA MENDES',
        bandeira: 'Elo',
        codigoSeguranca: '654',
        isPreferencial: true,
      },
    ],
  },
  {
    id: 'c4-jkl-012',
    nome: 'Roberto Fernandes',
    email: 'roberto.fernandes@empresa.com.br',
    genero: 'Masculino',
    telefone: { tipo: 'Comercial', ddd: '41', numero: '98877-1122' },
    cpf: '456.789.012-34',
    dataNascimento: '1979-01-30',
    ranking: 4,
    isAtivo: true,
    enderecos: [
      {
        id: 'end-c4-1',
        nome: 'Casa',
        tipo: 'ambos',
        tipoResidencia: 'Casa',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Padre Anchieta',
        numero: '1500',
        bairro: 'Batel',
        cep: '80420-011',
        cidade: 'Curitiba',
        estado: 'PR',
        pais: 'Brasil',
        observacoes: '',
      },
      {
        id: 'end-c4-2',
        nome: 'Trabalho',
        tipo: 'entrega',
        tipoResidencia: 'Comercial',
        tipoLogradouro: 'Avenida',
        logradouro: 'Avenida Cândido de Abreu',
        numero: '660',
        bairro: 'Centro Cívico',
        cep: '80530-000',
        cidade: 'Curitiba',
        estado: 'PR',
        pais: 'Brasil',
        observacoes: '',
      },
      {
        id: 'end-c4-3',
        nome: 'Casa da praia',
        tipo: 'entrega',
        tipoResidencia: 'Casa',
        tipoLogradouro: 'Avenida',
        logradouro: 'Avenida Atlântica',
        numero: '303',
        bairro: 'Centro',
        cep: '83280-000',
        cidade: 'Guaratuba',
        estado: 'PR',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [
      {
        id: 'car-c4-1',
        numero: '4024 0071 5533 8890',
        nomeImpresso: 'ROBERTO FERNANDES',
        bandeira: 'Visa',
        codigoSeguranca: '234',
        isPreferencial: true,
      },
      {
        id: 'car-c4-2',
        numero: '6062 8212 3456 7891',
        nomeImpresso: 'ROBERTO FERNANDES',
        bandeira: 'Hipercard',
        codigoSeguranca: '567',
        isPreferencial: false,
      },
    ],
  },
  {
    id: 'c5-mno-345',
    nome: 'Beatriz Souza',
    email: 'beatriz.souza@yahoo.com.br',
    genero: 'Feminino',
    telefone: { tipo: 'Celular', ddd: '11', numero: '91111-2222' },
    cpf: '567.890.123-45',
    dataNascimento: '1996-09-08',
    ranking: 5,
    isAtivo: true,
    enderecos: [
      {
        id: 'end-c5-1',
        nome: 'Apartamento',
        tipo: 'ambos',
        tipoResidencia: 'Apartamento',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Joaquim Nabuco',
        numero: '75',
        bairro: 'Moema',
        cep: '04070-010',
        cidade: 'São Paulo',
        estado: 'SP',
        pais: 'Brasil',
        observacoes: 'Portaria 24h, avisar o síndico se atrasar.',
      },
    ],
    cartoes: [
      {
        id: 'car-c5-1',
        numero: '5183 4467 2298 0013',
        nomeImpresso: 'BEATRIZ SOUZA',
        bandeira: 'Mastercard',
        codigoSeguranca: '890',
        isPreferencial: true,
      },
      {
        id: 'car-c5-2',
        numero: '4916 3382 1147 5620',
        nomeImpresso: 'BEATRIZ S SOUZA',
        bandeira: 'Visa',
        codigoSeguranca: '112',
        isPreferencial: false,
      },
      {
        id: 'car-c5-3',
        numero: '3055 8821 4470 0032',
        nomeImpresso: 'BEATRIZ SOUZA',
        bandeira: 'Diners Club',
        codigoSeguranca: '445',
        isPreferencial: false,
      },
    ],
  },
  {
    id: 'c6-pqr-678',
    nome: 'Marcos Vinícius Costa',
    email: 'marcos.costa@email.com',
    genero: 'Masculino',
    telefone: { tipo: 'Celular', ddd: '85', numero: '97766-5544' },
    cpf: '678.901.234-56',
    dataNascimento: '1993-05-17',
    ranking: 2,
    isAtivo: false,
    enderecos: [
      {
        id: 'end-c6-1',
        nome: 'Casa',
        tipo: 'ambos',
        tipoResidencia: 'Casa',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Barão de Aracati',
        numero: '620',
        bairro: 'Aldeota',
        cep: '60150-040',
        cidade: 'Fortaleza',
        estado: 'CE',
        pais: 'Brasil',
        observacoes: '',
      },
      {
        id: 'end-c6-2',
        nome: 'Trabalho',
        tipo: 'entrega',
        tipoResidencia: 'Comercial',
        tipoLogradouro: 'Avenida',
        logradouro: 'Avenida Beira Mar',
        numero: '3130',
        bairro: 'Meireles',
        cep: '60165-121',
        cidade: 'Fortaleza',
        estado: 'CE',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [],
  },
  {
    id: 'c7-stu-901',
    nome: 'Larissa Ribeiro',
    email: 'laribeiro@gmail.com',
    genero: 'Prefiro não informar',
    telefone: { tipo: 'Celular', ddd: '19', numero: '99898-7676' },
    cpf: '789.012.345-67',
    dataNascimento: '1990-12-05',
    ranking: 4,
    isAtivo: true,
    enderecos: [
      {
        id: 'end-c7-1',
        nome: 'Casa',
        tipo: 'cobranca',
        tipoResidencia: 'Casa',
        tipoLogradouro: 'Rua',
        logradouro: 'Rua Cônego Cipião',
        numero: '145',
        bairro: 'Cambuí',
        cep: '13024-380',
        cidade: 'Campinas',
        estado: 'SP',
        pais: 'Brasil',
        observacoes: '',
      },
      {
        id: 'end-c7-2',
        nome: 'Trabalho',
        tipo: 'entrega',
        tipoResidencia: 'Comercial',
        tipoLogradouro: 'Avenida',
        logradouro: 'Avenida José Bonifácio',
        numero: '515',
        bairro: 'Taquaral',
        cep: '13090-610',
        cidade: 'Campinas',
        estado: 'SP',
        pais: 'Brasil',
        observacoes: '',
      },
    ],
    cartoes: [
      {
        id: 'car-c7-1',
        numero: '4485 3321 7760 0098',
        nomeImpresso: 'LARISSA RIBEIRO',
        bandeira: 'Visa',
        codigoSeguranca: '321',
        isPreferencial: true,
      },
      {
        id: 'car-c7-2',
        numero: '3413 559821 40067',
        nomeImpresso: 'LARISSA RIBEIRO',
        bandeira: 'American Express',
        codigoSeguranca: '9012',
        isPreferencial: false,
      },
    ],
  },
];
