import type { Disco } from '../types/disco';

export const discosMock: Disco[] = [
  {
    id: 1435589,
    title: 'Astroworld',
    artist: 'Travis Scott',
    releaseYear: 2018,
    genres: ['Hip Hop'],
    styles: ['Trap', 'Pop Rap', 'Psychedelic'],
    price: 389,
    coverSrc: 'https://i.discogs.com/EJzFyUkI9IXsUCOxtvuwffxqZvIjplGNQFG7rIwOWAQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNTY0/NDgwLTE3NDM0MTk4/NjctNjcxNC5wbmc.jpeg',
    coverThumb: 'https://i.discogs.com/hETV3Hi2vTBIbECTGTa5YFWbSPxCUz8SSnz6mL6HUhY/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNTY0/NDgwLTE3NDM0MTk4/NjctNjcxNC5wbmc.jpeg',
    numForSale: 408,
    discogsUri: 'https://www.discogs.com/master/1435589-Travis-Scott-2-Astroworld',
    gravadora: 'Cactus Jack / Epic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'EPIC-19075871371',
    codigoBarras: '7891123456781',
    numeroFaixas: 17,
    duracao: '59:21',
    descricao:
      'Álbum conceitual de Travis Scott inspirado no parque de diversões Six Flags AstroWorld, fechado em Houston. A prensagem em vinil duplo preserva a variação de clima entre as faixas, do trap mais pesado aos interlúdios psicodélicos. Participações de Drake, Frank Ocean e The Weeknd completam o encarte.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 14,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-19',
    autorizacaoGerente: null,
  },
  {
    id: 861083,
    title: 'Currents',
    artist: 'Tame Impala',
    releaseYear: 2015,
    genres: ['Electronic', 'Rock'],
    styles: ['Psychedelic Rock', 'Indie Rock'],
    price: 349,
    coverSrc: 'https://i.discogs.com/0m9adSJO-pWPRlWpwczRCUJfTokcREPbsmZMprEs1-o/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyNTIx/MTEtMTY5NzM4MTkw/MS0yMjg3LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/IPQHVvwWF0XrYmhXnrfFJpKcb-1hJxdUBH7w7igdryw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyNTIx/MTEtMTY5NzM4MTkw/MS0yMjg3LmpwZWc.jpeg',
    numForSale: 478,
    discogsUri: 'https://www.discogs.com/master/861083-Tame-Impala-Currents',
    gravadora: 'Modular Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'MODVL105',
    codigoBarras: '7891123456798',
    numeroFaixas: 13,
    duracao: '51:04',
    descricao:
      'Terceiro disco do Tame Impala marca a virada de Kevin Parker para produções mais eletrônicas, sem abandonar as raízes psicodélicas da banda. A sequência de faixas foi pensada para ouvir do início ao fim, e o vinil em 180g reforça essa proposta de audição contínua. Uma referência do indie rock dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 320,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 9,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 8883,
    title: 'Thriller',
    artist: 'Michael Jackson',
    releaseYear: 1982,
    genres: ['Funk / Soul', 'Pop'],
    styles: ['Contemporary R&B', 'Disco', 'Soul'],
    price: 229,
    coverSrc: '/images/capas/thriller.jpg',
    numForSale: 5029,
    discogsUri: 'https://www.discogs.com/master/8883-Michael-Jackson-Thriller',
    gravadora: 'Epic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-picture-disc', 'ed-reprensagem'],
    codigoCatalogo: 'EPIC-38112',
    codigoBarras: '7891123456804',
    numeroFaixas: 9,
    duracao: '42:19',
    descricao:
      'O disco mais vendido da história do pop, com produção de Quincy Jones e faixas que ainda tocam em pistas de dança até hoje. Esta prensagem reproduz o layout original de capa e encarte da Epic. Um item essencial para qualquer coleção que passe por Michael Jackson.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 250,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 22,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 57279,
    title: 'The Miseducation Of Lauryn Hill',
    artist: 'Lauryn Hill',
    releaseYear: 1998,
    genres: ['Hip Hop', 'Funk / Soul'],
    styles: ['Conscious', 'Contemporary R&B'],
    price: 359,
    coverSrc: 'https://i.discogs.com/bTjtNom72YkK2FXCB3dQ9yPEMwlIP2Sp-H4cj832QlY/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5MTUw/NTIyLTE2MjM3NzE1/NjgtMTI5Ni5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/hPenBr9Tv2SNAXAOxwLwDMWjjPTcnI6VnWwP9HnEGwU/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5MTUw/NTIyLTE2MjM3NzE1/NjgtMTI5Ni5qcGVn.jpeg',
    numForSale: 1401,
    discogsUri: 'https://www.discogs.com/master/57279-Lauryn-Hill-The-Miseducation-Of-Lauryn-Hill',
    gravadora: 'Ruffhouse / Columbia',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'RUFF-C2-69035',
    codigoBarras: '7891123457153',
    numeroFaixas: 16,
    duracao: '77:39',
    descricao:
      'Único álbum solo de Lauryn Hill, gravado depois da saída dos Fugees, cruzando hip hop, soul e reggae num só disco. Os interlúdios de sala de aula amarram as faixas e ganham fôlego na prensagem dupla, que espalha as dezesseis músicas por quatro lados. Marco do neo soul dos anos 1990 e vencedor de cinco Grammys.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 11,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-30',
    autorizacaoGerente: null,
  },
  {
    id: 10362,
    title: 'The Dark Side Of The Moon',
    artist: 'Pink Floyd',
    releaseYear: 1973,
    genres: ['Rock'],
    styles: ['Prog Rock', 'Psychedelic Rock'],
    price: 299,
    coverSrc: 'https://i.discogs.com/mwWMy1jLJhX7BGUigOAzbMQjmN6y2a9ppdzulDAUYSU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTQ3MTEwMDM4/MS0zMDIyLmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/3E0sabyyOSAx9e4wHdlBP7v31SDWvPooA3nAh_rqaB8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTQ3MTEwMDM4/MS0zMDIyLmpwZWc.jpeg',
    numForSale: 8376,
    discogsUri: 'https://www.discogs.com/master/10362-Pink-Floyd-The-Dark-Side-Of-The-Moon',
    gravadora: 'Harvest / EMI',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-remasterizado'],
    codigoCatalogo: 'HAR-SHVL804',
    codigoBarras: '7891123456828',
    numeroFaixas: 10,
    duracao: '42:59',
    descricao:
      'Um dos discos mais ouvidos do rock progressivo, gravado pelo Pink Floyd nos estúdios Abbey Road. A remasterização preservada nesta prensagem mantém a dinâmica original entre os efeitos sonoros e os instrumentos. Peça central para quem estuda a história do álbum conceitual.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 18,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-20',
    autorizacaoGerente: null,
  },
  {
    id: 810214,
    title: 'To Pimp A Butterfly',
    artist: 'Kendrick Lamar',
    releaseYear: 2015,
    genres: ['Hip Hop', 'Jazz', 'Funk / Soul'],
    styles: ['Conscious', 'Jazzy Hip-Hop', 'G-Funk', 'Neo Soul'],
    price: 369,
    coverSrc: 'https://i.discogs.com/8ZD7MZypmyxuliTV-Czyy03rA9ou2E-BL2rhIFTLUlk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY3ODEy/ODYtMTU4NjA5MTU4/OC04ODQ5LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/DLLwBajeE5HO1FICW8LDkw5OVdP2_v0yDI1k9VtajXI/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY3ODEy/ODYtMTU4NjA5MTU4/OC04ODQ5LmpwZWc.jpeg',
    numForSale: 754,
    discogsUri: 'https://www.discogs.com/master/810214-Kendrick-Lamar-To-Pimp-A-Butterfly',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0002-LP',
    codigoBarras: '7891123456811',
    numeroFaixas: 16,
    duracao: '78:51',
    descricao:
      'Kendrick Lamar mistura jazz, funk e spoken word numa obra densa sobre raça e identidade nos Estados Unidos. A duração estendida das faixas pede o formato duplo, com gatefold que traz as letras impressas. Um dos discos mais discutidos do hip hop na década de 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 470,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 11,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-18',
    autorizacaoGerente: null,
  },
  {
    id: 6440,
    title: 'Ride The Lightning',
    artist: 'Metallica',
    releaseYear: 1984,
    genres: ['Rock'],
    styles: ['Thrash', 'Speed Metal'],
    price: 259,
    coverSrc: 'https://i.discogs.com/h1yENH5BKaZ5b56zwsmWj0H7WjmUfRVLqT0y-ONqyfU/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzQ2/NC0xNzUzNTMwNjEz/LTExNzYuanBlZw.jpeg',
    coverThumb: 'https://i.discogs.com/FVh5oI_zt6hbb7uTx_Vr09ziPk6rksRUPE2rITpl8N0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzQ2/NC0xNzUzNTMwNjEz/LTExNzYuanBlZw.jpeg',
    numForSale: 1891,
    discogsUri: 'https://www.discogs.com/master/6440-Metallica-Ride-The-Lightning',
    gravadora: 'Elektra',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'ELK-60396',
    codigoBarras: '7891123456835',
    numeroFaixas: 8,
    duracao: '46:58',
    descricao:
      'Segundo disco do Metallica, ainda dentro do thrash metal mais cru da banda antes do estouro comercial. A prensagem nacional segue o encarte clássico da Elektra, sem alterações de faixa. Recomendado para quem busca o metal oitentista em sua forma mais direta.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 7,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-12',
    autorizacaoGerente: null,
  },
  {
    id: 593987,
    title: 'AM',
    artist: 'Arctic Monkeys',
    releaseYear: 2013,
    genres: ['Rock'],
    styles: ['Alternative Rock', 'Indie Rock'],
    price: 279,
    coverSrc: 'https://i.discogs.com/-5VP_faWPuZm-_4156UfRx0a_Wh8c5YKFS-GYgmeN_Y/rs:fit/g:sm/q:90/h:566/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ4ODM1/MDUtMTYxNjkyNTU1/OC0xMTY2LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/-WYv-8-UoeSHAAC0qq5vPWDE2uoH1arFPatzP_voph8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ4ODM1/MDUtMTYxNjkyNTU1/OC0xMTY2LmpwZWc.jpeg',
    numForSale: 661,
    discogsUri: 'https://www.discogs.com/master/593987-Arctic-Monkeys-AM',
    gravadora: 'Domino Recording Co.',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'DOM-WIGLP314',
    codigoBarras: '7891123456842',
    numeroFaixas: 12,
    duracao: '40:56',
    descricao:
      'Quinto álbum do Arctic Monkeys aposta em riffs mais lentos e um clima noturno que se afastou do indie rock dos primeiros discos da banda. A cor do vinil varia entre as tiragens, mas a faixa e a masterização seguem o mesmo padrão. Um disco que ajudou a definir o som da banda na década seguinte.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 16,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 35665,
    title: 'Mezmerize',
    artist: 'System Of A Down',
    releaseYear: 2005,
    genres: ['Rock'],
    styles: ['Alternative Metal', 'Avantgarde'],
    price: 239,
    coverSrc: 'https://i.discogs.com/SCUBA6-lWnMyCqA-rOn83ZXjJDKi3p7mq1krUIgKfcQ/rs:fit/g:sm/q:90/h:543/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1ODcw/Ny0xMjQ2NzU4OTk2/LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/EKi93r8KpGf7V8XWjc-t8TEmrT5JgBlgN4qM0pROAg8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1ODcw/Ny0xMjQ2NzU4OTk2/LmpwZWc.jpeg',
    numForSale: 547,
    discogsUri: 'https://www.discogs.com/master/35665-System-Of-A-Down-Mezmerize',
    gravadora: 'American Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-remasterizado'],
    codigoCatalogo: 'AMR-0602547',
    codigoBarras: '7891123456859',
    numeroFaixas: 11,
    duracao: '35:39',
    descricao:
      'Quarto disco do System Of A Down, gravado junto com o Hypnotize numa mesma sessão de estúdio. A prensagem reedição de 2017 manteve o encarte original com as letras de Serj Tankian e Daron Malakian. Um retrato do metal alternativo do início dos anos 2000.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 250,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 0,
    isAtivo: false,
    motivoStatus: {
      categoria: 'BAIXA DEMANDA',
      justificativa:
        'Giro baixo nos últimos meses; prioridade de espaço para títulos com mais saída.',
      data: '2026-02-02',
      automatico: false,
    },
    ultimaVendaEm: '2026-01-27',
    autorizacaoGerente: null,
  },
  {
    id: 1112335,
    title: 'Awaken, My Love!',
    artist: 'Childish Gambino',
    releaseYear: 2016,
    genres: ['Funk / Soul'],
    styles: ['Contemporary R&B', 'Funk', 'Neo Soul', 'Psychedelic'],
    price: 319,
    coverSrc: 'https://i.discogs.com/ntpLgSprFAaAUdPEcdkdjuTv1dCPVp7Hp2T5Cwqi-HU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMzUw/MTg4LTE2Mzk1MDQ5/NDgtNDcwNS5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/Nw037wPFLZWXe6PA7Nzf5-_bJaXTaevr8ZSEH0sdOIc/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMzUw/MTg4LTE2Mzk1MDQ5/NDgtNDcwNS5qcGVn.jpeg',
    numForSale: 266,
    discogsUri: 'https://www.discogs.com/master/1112335-Childish-Gambino-Awaken-My-Love',
    gravadora: 'Glassnote Records',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'GLS-2521',
    codigoBarras: '7891123456866',
    numeroFaixas: 11,
    duracao: '57:57',
    descricao:
      'Childish Gambino troca o rap dos discos anteriores por funk e soul psicodélico, numa homenagem clara a Funkadelic. O encarte gatefold do vinil duplo traz o mesmo clima visual da capa, com Donald Glover em tons esverdeados. Um disco que surpreendeu quem esperava outro álbum de hip hop.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.9,
      peso: 460,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 5,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-09',
    autorizacaoGerente: null,
  },
  {
    id: 950545,
    title: 'Anti',
    artist: 'Rihanna',
    releaseYear: 2016,
    genres: ['Hip Hop', 'Pop'],
    styles: ['Contemporary R&B', 'Soul'],
    price: 359,
    coverSrc: 'https://i.discogs.com/mg1yxMcWPITNIRcd0KTbwybqqqJ_tWDAeG5OBOAS1Cw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgwNDkx/NTAtMTQ1NDE2ODc0/OC0yNjI1LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/gqFojgF3eXHh2AZSXE5fpJrgoR6VvB7jZn8xYfPHwcE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgwNDkx/NTAtMTQ1NDE2ODc0/OC0yNjI1LmpwZWc.jpeg',
    numForSale: 238,
    discogsUri: 'https://www.discogs.com/master/950545-Rihanna-Anti',
    gravadora: 'Westbury Road Entertainment',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'WBR-2016-LP',
    codigoBarras: '0602557193281',
    numeroFaixas: 13,
    duracao: '43:50',
    descricao:
      'Rihanna abandona as fórmulas de hit single para um disco mais introspectivo, gravado ao longo de anos de sessões dispersas. A prensagem em vinil translúcido acompanha o encarte com as letras completas. Um ponto de virada na carreira da artista.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 4,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-07-30',
    autorizacaoGerente: 'Rodrigo Rocha — 12/07/2026',
  },
  {
    id: 1164779,
    title: 'Damn',
    artist: 'Kendrick Lamar',
    releaseYear: 2017,
    genres: ['Hip Hop', 'Funk / Soul'],
    styles: ['Conscious', 'Contemporary R&B', 'Jazzy Hip-Hop', 'Trap', 'Boom Bap'],
    price: 339,
    coverSrc: 'https://i.discogs.com/n9BtVuF-dJtmghgg5MhBtN_nME-Wqb4SboSfeBxnWVE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTMz/NTM4LTE0OTIyMDQ5/NjMtMzE5Ni5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/5gflVLxiFzEVd6bMZhfLHTmg7li-O4PgDpaFubQJO3M/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTMz/NTM4LTE0OTIyMDQ5/NjMtMzE5Ni5qcGVn.jpeg',
    numForSale: 607,
    discogsUri: 'https://www.discogs.com/master/1164779-Kendrick-Lamar-Damn',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0006-LP',
    codigoBarras: '7891123456873',
    numeroFaixas: 14,
    duracao: '54:54',
    descricao:
      'Kendrick Lamar alterna faixas de contemplação religiosa com produções mais diretas para rádio, num disco que rendeu o Pulitzer de música. A capa reversível desta prensagem permite trocar entre o título em preto e em vermelho. Um marco do hip hop consciente da década.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 13,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 13814,
    title: "Nevermind",
    artist: "Nirvana",
    releaseYear: 1991,
    genres: ["Rock"],
    styles: ["Grunge", "Alternative Rock"],
    price: 289,
    coverSrc: "https://i.discogs.com/os3Gm61mroiZvEw2bIGtNDf0RXydEx8PRmIk-YYwBSU/rs:fit/g:sm/q:90/h:600/w:594/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4MTMw/MDYtMTQzNjgxNDc2/Mi05NjgxLmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/TcLhjpdmx3MmaXiqlQZbPOskOdPkxDcfwtS8TIp9tvo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4MTMw/MDYtMTQzNjgxNDc2/Mi05NjgxLmpwZWc.jpeg",
    numForSale: 3505,
    discogsUri: "https://www.discogs.com/master/13814-Nirvana-Nevermind",
    gravadora: "DGC / Sub Pop",
    formatoId: 'fmt-lp',
    edicaoIds: ["ed-reprensagem", "ed-remasterizado"],
    codigoCatalogo: 'NEVERMIND-13814',
    codigoBarras: '7891123457112',
    numeroFaixas: 12,
    duracao: '42:11',
    descricao:
      "Segundo álbum do Nirvana levou o grunge de Seattle para o mainstream e desalojou Michael Jackson do topo da parada americana. A remasterização mantém a mixagem de Andy Wallace que definiu o som do disco. Uma porta de entrada obrigatória para o rock dos anos 1990.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 20,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 1473270,
    title: 'Not All Heroes Wear Capes',
    artist: 'Metro Boomin',
    releaseYear: 2018,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 359,
    coverSrc: 'https://i.discogs.com/Jqu3KIN38JhzhDbC97NzhZ9e-tlFZ8R7v9ZD9UVe-co/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyMjc2/NDQxLTE2NDU2MzU1/MzAtOTE4Mi5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/9Tmv9Xs5QDQL0-P1xP_pV20jcCq9mIQccee91Wk1g0o/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyMjc2/NDQxLTE2NDU2MzU1/MzAtOTE4Mi5qcGVn.jpeg',
    numForSale: 52,
    discogsUri: 'https://www.discogs.com/master/1473270-Metro-Boomin-Not-All-Heroes-Wear-Capes',
    gravadora: 'Boominati Worldwide',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'BMW-71234',
    codigoBarras: '0060254712349',
    numeroFaixas: 13,
    duracao: '44:18',
    descricao:
      'Primeiro álbum solo de Metro Boomin reúne parceiros de longa data como 21 Savage, Travis Scott e Kodak Black sob sua produção característica. A prensagem importada segue o encarte simples da edição americana. Um retrato do trap de produtor que marcou o final dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 3,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-05',
    autorizacaoGerente: null,
  },
  {
    id: 1085420,
    title: 'Birds In The Trap Sing McKnight',
    artist: 'Travis Scott',
    releaseYear: 2016,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 369,
    coverSrc: 'https://i.discogs.com/awwmHLs5RtRYcnFH5FcIe9WN4MPgpoegnJEBXWdBR0E/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5ODky/OTgtMTU0OTA1MzE4/NS0yNzE0LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/78nVRc30OdpufthaN_Gl9IBRMZw4Fk-Tx3UwF_WJpJA/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5ODky/OTgtMTU0OTA1MzE4/NS0yNzE0LmpwZWc.jpeg',
    numForSale: 267,
    discogsUri: 'https://www.discogs.com/master/1085420-Travis-Scott-2-Birds-In-The-Trap-Sing-McKnight',
    gravadora: 'Grand Hustle / Epic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'EPIC-B12016LP',
    codigoBarras: '0886985031382',
    numeroFaixas: 14,
    duracao: '48:32',
    descricao:
      'Segundo álbum de estúdio de Travis Scott, com produção que mistura trap e texturas psicodélicas mais experimentais que o disco de estreia. A cor do vinil varia entre as tiragens importadas, mas a faixa segue o encarte original. Participações de Kendrick Lamar e André 3000 completam o disco.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-02-10',
    autorizacaoGerente: null,
  },
  {
    id: 4119973,
    title: 'Octane',
    artist: 'Don Toliver',
    releaseYear: 2026,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 329,
    coverSrc: 'https://i.discogs.com/Uws6X_YtdeyigTLt0zdApEfE2gdJxuBDVgMyHvsNcu8/rs:fit/g:sm/q:90/h:592/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NTI1/MDY0LTE3NzEyNzM3/MjMtNzg0OS5wbmc.jpeg',
    coverThumb: 'https://i.discogs.com/OayNp9uSDx5JKXlKQIXBP7RfP98sQNCrzGPX_QBwnl0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NTI1/MDY0LTE3NzEyNzM3/MjMtNzg0OS5wbmc.jpeg',
    numForSale: 109,
    discogsUri: 'https://www.discogs.com/master/4119973-Don-Toliver-Octane',
    gravadora: 'Cactus Jack / Atlantic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'ATL-2026114',
    codigoBarras: '7891123456880',
    numeroFaixas: 18,
    duracao: '52:10',
    descricao:
      'Novo álbum de Don Toliver, ainda no giro alto de vendas típico das primeiras semanas de lançamento. A prensagem simples em vinil acompanha um encarte numerado, próprio das primeiras tiragens. Um disco recente que já figura entre os mais buscados da loja.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 25,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-23',
    autorizacaoGerente: null,
  },
  {
    id: 8497,
    title: 'Graduation',
    artist: 'Kanye West',
    releaseYear: 2007,
    genres: ['Hip Hop', 'Funk / Soul'],
    styles: ['Contemporary R&B', 'Pop Rap'],
    price: 309,
    coverSrc: 'https://i.discogs.com/ZGCZsgTZlSxAbspOky80WD6jI_tc6zoJuXfqZAEWYkI/rs:fit/g:sm/q:90/h:537/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNjY2/MDEtMTYzMjU2Nzcx/Mi0xNTg2LnBuZw.jpeg',
    coverThumb: 'https://i.discogs.com/-iyDPlWlmsbQakNdM0GiYCT6oYZCmxjpKSDmSmlT0JI/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNjY2/MDEtMTYzMjU2Nzcx/Mi0xNTg2LnBuZw.jpeg',
    numForSale: 167,
    discogsUri: 'https://www.discogs.com/master/8497-kanYeWest-Graduation',
    gravadora: 'Roc-A-Fella / Def Jam',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'DEF-0601811',
    codigoBarras: '7891123456897',
    numeroFaixas: 13,
    duracao: '52:09',
    descricao:
      'Terceiro disco de Kanye West marca a virada do rapper para produções mais eletrônicas e influenciadas por rock de estádios. O gatefold desta reedição traz as ilustrações de Takashi Murakami usadas na capa original. Um divisor de águas entre o Kanye de Late Registration e a fase mais pop dos discos seguintes.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 320,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 8,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-17',
    autorizacaoGerente: null,
  },
  {
    id: 2670629,
    title: 'Un Verano Sin Ti',
    artist: 'Bad Bunny',
    releaseYear: 2022,
    genres: ['Electronic', 'Hip Hop', 'Reggae', 'Latin', 'Pop'],
    styles: ['Reggaeton', 'Trap', 'Synth-pop', 'House', 'Reggae', 'Mambo', 'Latin Pop'],
    price: 399,
    coverSrc: 'https://i.discogs.com/AVfnmTckGhWNpTOluDOLMqAXo-lwDuK8RK-zRw7DjUo/rs:fit/g:sm/q:90/h:528/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MTEy/NTIwLTE2NjE2NTUx/ODQtMTg3NC5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/sdGdZU0Qy2xyUPxZDZnqR95MWhBROvzF4Ox2bTCURpI/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MTEy/NTIwLTE2NjE2NTUx/ODQtMTg3NC5qcGVn.jpeg',
    numForSale: 3,
    discogsUri: 'https://www.discogs.com/master/2670629-Bad-Bunny-Un-Verano-Sin-Ti',
    gravadora: 'Rimas Entertainment',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'RIM-2022UVST',
    codigoBarras: '6061234567892',
    numeroFaixas: 23,
    duracao: '81:14',
    descricao:
      'Bad Bunny expande o reggaeton para o pop e para ritmos caribenhos como bomba e plena, num disco que dominou as paradas globais. A prensagem em vinil duplo importado segue o gatefold da edição internacional. Ainda sem saída de estoque nesta loja, apesar da procura constante pelo título.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: null,
    autorizacaoGerente: null,
  },
  {
    id: 883244,
    title: 'Rodeo',
    artist: 'Travis Scott',
    releaseYear: 2015,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 379,
    coverSrc: 'https://i.discogs.com/IvgsheLssaAfZNjFGiQK1k59Hzw4NYJ6F_sackrd9H0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNjAz/MDI4LTE3MzQ1NTQ0/NDEtOTQ2NC5wbmc.jpeg',
    coverThumb: 'https://i.discogs.com/6ZseCJ7Lz0DQQJdGCnQmhPh75JazwyBg43bn_W5OIaE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNjAz/MDI4LTE3MzQ1NTQ0/NDEtOTQ2NC5wbmc.jpeg',
    numForSale: 232,
    discogsUri: 'https://www.discogs.com/master/883244-Travis-Scott-2-Rodeo',
    gravadora: 'Grand Hustle / Epic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'EPIC-R15LP2',
    codigoBarras: '0889854021479',
    numeroFaixas: 14,
    duracao: '65:57',
    descricao:
      'Álbum de estreia de Travis Scott, com produção que aproxima trap e rock psicodélico, num som que o artista aprofundaria nos discos seguintes. A tiragem importada em vinil colorido segue o encarte duplo original. Participações de Kanye West, Toro y Moi e The Weeknd marcam a lista de faixas.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 490,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 6,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-14',
    autorizacaoGerente: null,
  },
  {
    id: 4155436,
    title: 'Thy Will Be Done',
    artist: '$uicideboy$',
    releaseYear: 2026,
    genres: ['Hip Hop'],
    styles: ['Hardcore Hip-Hop', 'Trap', 'Cloud Rap'],
    price: 299,
    coverSrc: 'https://i.discogs.com/p2KgWoTCRME4SVR6vq1Q6G1ULgDSnaj3KOmOOKP0QQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2Njk2/Nzk5LTE3NzMwOTM1/MjMtNjcwNi5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/pfQz48F0KFtnzfoTTBgV4p-rtWd71pQ82bEbmJLYFZo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2Njk2/Nzk5LTE3NzMwOTM1/MjMtNjcwNi5qcGVn.jpeg',
    numForSale: 120,
    discogsUri: 'https://www.discogs.com/master/4155436-uicideboy-Thy-Will-Be-Done',
    gravadora: 'G59 Records',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'G59-2026TWBD',
    codigoBarras: '7891123456903',
    numeroFaixas: 10,
    duracao: '38:24',
    descricao:
      'Novo lançamento do duo $uicideboy$, que segue na linha de horrorcore e trap sombrio construída desde os primeiros mixtapes do grupo. A tiragem em vinil colorido numerado esgotou rápido nesta loja, ainda no mês de lançamento. Uma prensagem de tiragem limitada, sem previsão de reposição.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-19',
    autorizacaoGerente: null,
  },
  {
    id: 3716847,
    title: 'Debí Tirar Más Fotos',
    artist: 'Bad Bunny',
    releaseYear: 2025,
    genres: ['Electronic', 'Hip Hop', 'Latin', 'Pop'],
    styles: ['Reggaeton', 'Salsa', 'Aguinaldo', 'Bomba', 'Plena', 'Trap', 'Hip Hop', 'House', 'Latin Pop'],
    price: 389,
    coverSrc: 'https://i.discogs.com/sKdg2-UawQ7QzMOqg7VXpJktykbjEloglXcmb-4jk1E/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyODE3/NDAyLTE3MzY2MjA3/NTctMzY3Ni5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/mpQTRqxCnw4qFeOC3iXuHzkRPXPrAkw9Ebd1lVzqnGY/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyODE3/NDAyLTE3MzY2MjA3/NTctMzY3Ni5qcGVn.jpeg',
    numForSale: 319,
    discogsUri: 'https://www.discogs.com/master/3716847-Bad-Bunny-Debí-Tirar-Más-Fotos',
    gravadora: 'Rimas Entertainment',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'RIM-2025DTMF',
    codigoBarras: '7891123456910',
    numeroFaixas: 17,
    duracao: '52:16',
    descricao:
      'Bad Bunny retorna às raízes porto-riquenhas com um disco que passeia por salsa, plena e reggaeton clássico. A prensagem de lançamento traz um encarte com fotos do processo de gravação. Um dos títulos mais procurados do catálogo latino da loja.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 19,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 288153,
    title: 'My Beautiful Dark Twisted Fantasy',
    artist: 'Kanye West',
    releaseYear: 2010,
    genres: ['Hip Hop'],
    styles: ['Pop Rap', 'Contemporary R&B'],
    price: 429,
    coverSrc: 'https://i.discogs.com/3RRJgAX-aSq0JB4tAZBpdWQezFQPiDauBE9eV0uhEAM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTkx/NTItMTczMTcxMzky/OC01OTQ0LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/5HSWaCap9BqOtqSxnOKWA1YmoU2vBvhHNe8CB4P5L74/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTkx/NTItMTczMTcxMzky/OC01OTQ0LmpwZWc.jpeg',
    numForSale: 459,
    discogsUri: 'https://www.discogs.com/master/288153-Kanye-West-My-Beautiful-Dark-Twisted-Fantasy',
    gravadora: 'GOOD Music / Def Jam',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'GOOD-0602527',
    codigoBarras: '0602527730951',
    numeroFaixas: 14,
    duracao: '68:23',
    descricao:
      'Quinto disco de Kanye West é considerado por muita gente o ápice de sua fase de produção mais orquestral e maximalista. A prensagem importada em vinil duplo mantém o gatefold com a arte de George Condo. Participações de Rick Ross, Nicki Minaj e Bon Iver reforçam o caráter coletivo do projeto.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 500,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 2,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-16',
    autorizacaoGerente: null,
  },
  {
    id: 454284,
    title: 'Channel Orange',
    artist: 'Frank Ocean',
    releaseYear: 2012,
    genres: ['Hip Hop', 'Funk / Soul', 'Pop'],
    styles: ['Contemporary R&B', 'Soul', 'Neo Soul'],
    price: 419,
    coverSrc: 'https://i.discogs.com/T194rRO-vNdN71vM_XUorDW2B3kNN5X4EwFDweUtDlc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MzEx/ODUtMTc0NTQ0NzIy/Ni05NTIzLmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/Cl6ABRkrFJZ1t3yrCajvV72UnfIN_1ah2iHe7CazdNc/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MzEx/ODUtMTc0NTQ0NzIy/Ni05NTIzLmpwZWc.jpeg',
    numForSale: 255,
    discogsUri: 'https://www.discogs.com/master/454284-Frank-Ocean-Channel-Orange',
    gravadora: 'Def Jam Recordings',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'DEF-0602537',
    codigoBarras: '0602537123457',
    numeroFaixas: 19,
    duracao: '62:29',
    descricao:
      'Álbum de estreia de Frank Ocean fora do coletivo Odd Future, com um R&B mais introspectivo e cheio de interlúdios narrativos. A prensagem importada em vinil duplo colorido segue o layout original de faixas. Um disco que ajudou a redefinir o R&B contemporâneo dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 470,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 5,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-13',
    autorizacaoGerente: null,
  },
  {
    id: 3975953,
    title: 'Good Kid, M.A.A.D City (Deluxe Edition)',
    artist: 'Kendrick Lamar',
    releaseYear: 2012,
    genres: ['Hip Hop'],
    styles: ['Conscious'],
    price: 419,
    coverSrc: 'https://i.discogs.com/m8eUFdh6Dmu3VIwfNJUNI8Eht0dZfJyB9ycEYgatQdY/rs:fit/g:sm/q:90/h:588/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5NzU5/NTMtMTU3MDQwNDc5/NS01Njk0LmpwZWc.jpeg',
    coverThumb: 'https://i.discogs.com/bWN4wGLGobx-8DJ3C5D-_actD7W-kuVQyWE1uqVkz1Q/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5NzU5/NTMtMTU3MDQwNDc5/NS01Njk0LmpwZWc.jpeg',
    numForSale: 70,
    discogsUri: 'https://www.discogs.com/release/3975953-Kendrick-Lamar-Good-Kid-MAAD-City',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0001-LP-DX',
    codigoBarras: '0602537891234',
    numeroFaixas: 15,
    duracao: '78:53',
    descricao:
      'Edição estendida do álbum de estreia de Kendrick Lamar pela major, com faixas bônus que não constam na versão padrão. A prensagem importada em vinil duplo já não é mais fabricada, o que a torna uma das poucas formas físicas de acessar essas faixas extras. Um documento da chegada de Kendrick ao mainstream.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 500,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: false,
    motivoStatus: {
      categoria: 'FORA DE LINHA',
      justificativa:
        'Edição deluxe saiu de linha do fornecedor, sem previsão de nova prensagem.',
      data: '2025-12-10',
      automatico: false,
    },
    ultimaVendaEm: '2025-11-04',
    autorizacaoGerente: null,
  },
  {
    id: 3227581,
    title: 'Michael',
    artist: 'Killer Mike',
    releaseYear: 2023,
    genres: ['Hip Hop'],
    styles: [],
    price: 319,
    coverSrc: 'https://i.discogs.com/HjSnYQqDpXzsptDgtitRJVoqP-xUm8dWmSeEMMWIq34/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NDAz/MTk0LTE2ODY5NDc2/NDAtODE2MC5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/zjahQjt4t8ET8bTlfRqICRVDay9kJVs5ivJ4zFTWG2w/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NDAz/MTk0LTE2ODY5NDc2/NDAtODE2MC5qcGVn.jpeg',
    numForSale: 172,
    discogsUri: 'https://www.discogs.com/master/3227581-Killer-Mike-Michael',
    gravadora: 'Loma Vista Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'LOMA-23018',
    codigoBarras: '7891123456927',
    numeroFaixas: 14,
    duracao: '53:33',
    descricao:
      'Disco de Killer Mike depois do sucesso do Run The Jewels, com produção que dialoga com gospel e soul do sul dos Estados Unidos. A reedição em 180g mantém o encarte original com participações de André 3000 e Future. Um retorno ao trabalho solo que rendeu ao rapper o Grammy de melhor álbum de rap.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 10,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-11',
    autorizacaoGerente: null,
  },
  {
    id: 2890219,
    title: 'Heroes & Villains',
    artist: 'Metro Boomin',
    releaseYear: 2022,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 369,
    coverSrc: 'https://i.discogs.com/n21h0GO52Iw6d_vhdqXdAi3H5jlkSBf8kp4yYsaVDaU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1MzUx/MDIxLTE3NTQwMDEz/NjgtNTExMS5qcGVn.jpeg',
    coverThumb: 'https://i.discogs.com/hBP1fLzfjbEux-lvxHZlAwGyQYz8-fPtVCXlhQ4vlx0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1MzUx/MDIxLTE3NTQwMDEz/NjgtNTExMS5qcGVn.jpeg',
    numForSale: 109,
    discogsUri: 'https://www.discogs.com/master/2890219-Metro-Boomin-Heroes-Villains',
    gravadora: 'Boominati Worldwide / Republic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'BMW-22HV002',
    codigoBarras: '0060254789013',
    numeroFaixas: 15,
    duracao: '53:57',
    descricao:
      'Segundo álbum solo de Metro Boomin, com uma lista de participações que passa por Travis Scott, Future e The Weeknd. A prensagem importada em vinil duplo mantém o gatefold da edição americana. Um disco que consolidou o produtor como nome de peso fora dos créditos de estúdio.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 7,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-20',
    autorizacaoGerente: null,
  },
  {
    id: 573645,
    title: "Rita Lee",
    artist: "Rita Lee",
    releaseYear: 1979,
    genres: ["Rock", "Latin", "Funk / Soul", "Pop"],
    styles: ["Pop Rock", "Disco", "Rock & Roll", "Art Rock"],
    price: 249,
    coverSrc: "https://i.discogs.com/IAcjfhzKvW-QvHhbVjJlDrO4l9vhOb8RyAHx1UMguBk/rs:fit/g:sm/q:90/h:596/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTk2/MzgtMTM5MjQ4MDE1/Mi04OTQ1LmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/HmujJ1aHKx9wUigkpZwm6O8RWn_-xtA0RMRJgoyvE-I/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTk2/MzgtMTM5MjQ4MDE1/Mi04OTQ1LmpwZWc.jpeg",
    numForSale: 40,
    discogsUri: "https://www.discogs.com/master/573645-Rita-Lee-Rita-Lee",
    gravadora: 'Som Livre',
    formatoId: 'fmt-lp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'RITALEE-573645',
    codigoBarras: '7891123457007',
    numeroFaixas: 8,
    duracao: '33:00',
    descricao:
      "Álbum de 1979 que traz Mania De Você, Doce Vampiro e Chega Mais, com Rita Lee circulando entre rock and roll, disco e pop numa mesma sequência de faixas. A reprensagem nacional mantém a arte original da Som Livre. Um dos discos mais tocados da carreira dela.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 12,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-18',
    autorizacaoGerente: null,
  },
  {
    id: 841256,
    title: "At. Long. Last. A$AP",
    artist: "ASAP Rocky",
    releaseYear: 2015,
    genres: ["Hip Hop"],
    styles: ["Trap", "Cloud Rap", "Psychedelic"],
    price: 419,
    coverSrc: "https://i.discogs.com/J2Us3aoTC3TaTX9vOi8qXNgQKlqawMrfpQ1TlsSlwb4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNTM0/MTUtMTQzMjYxMTE3/Mi02NzQ4LmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/HrJNXxtf7MEU8ETknL10U1_B5AW64kq2dIFaPfJfdGM/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNTM0/MTUtMTQzMjYxMTE3/Mi02NzQ4LmpwZWc.jpeg",
    numForSale: 233,
    discogsUri: "https://www.discogs.com/master/841256-AAP-Rocky-At-Long-Last-AAP",
    gravadora: "RCA / Polo Grounds",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'ALLA-841256',
    codigoBarras: '7891123457014',
    numeroFaixas: 18,
    duracao: '66:09',
    descricao:
      "Segundo álbum de A$AP Rocky, com produção psicodélica que se afasta do cloud rap do disco anterior. O vinil duplo acomoda as faixas mais longas sem cortar a dinâmica das transições. Participações de Rod Stewart, Miguel e Kanye West aparecem no encarte.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 6,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-15',
    autorizacaoGerente: null,
  },
  {
    id: 430850,
    title: "Nada Como Um Dia Após O Outro Dia",
    artist: "Racionais MC's",
    releaseYear: 2002,
    genres: ["Hip Hop", "Latin", "Funk / Soul"],
    styles: ["Gangsta", "Conscious"],
    price: 379,
    coverSrc: "https://i.discogs.com/nNBMBF1wezph85GUW4l_G6moxChjU5h0R1b83SDkx1Y/rs:fit/g:sm/q:90/h:586/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3OTAy/Mi0xNTg4MjIyMTk0/LTk3NTIuanBlZw.jpeg",
    coverThumb: "https://i.discogs.com/FpYpDZOtx5yITMQwK6gI6M1pSXpgg089SK_YS8XZxfo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3OTAy/Mi0xNTg4MjIyMTk0/LTk3NTIuanBlZw.jpeg",
    numForSale: 18,
    discogsUri: "https://www.discogs.com/master/430850-Racionais-MCs-Nada-Como-Um-Dia-Após-O-Outro-Dia",
    gravadora: "Cosa Nostra",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'NADACOMO-430850',
    codigoBarras: '7891123457021',
    numeroFaixas: 21,
    duracao: '110:33',
    descricao:
      "Álbum duplo dos Racionais MC's gravado depois de Sobrevivendo No Inferno, dividido entre um lado mais melódico e outro de rap cru. A reprensagem nacional recupera o encarte com as letras completas. Documento essencial do rap brasileiro dos anos 2000.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 15,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 511822,
    title: "Long.Live.A$AP",
    artist: "ASAP Rocky",
    releaseYear: 2013,
    genres: ["Electronic", "Hip Hop"],
    styles: ["Cloud Rap", "Trap", "Electro", "Pop Rap", "Experimental"],
    price: 389,
    coverSrc: "https://i.discogs.com/SAf4ukaCCH6TZaY5REB-g9m1F5Bc9HaVvsBiVwAIxgc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQyMjY1/NDktMTM1OTA3OTk2/OC00ODM5LmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/cxqAtkS0zBId7DuZzfgoGnNDUreDt0mW9m2wI10y-9Y/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQyMjY1/NDktMTM1OTA3OTk2/OC00ODM5LmpwZWc.jpeg",
    numForSale: 249,
    discogsUri: "https://www.discogs.com/master/511822-AAP-Rocky-LongLiveAAP",
    gravadora: 'RCA / Polo Grounds',
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'LLASAP-511822',
    codigoBarras: '7891123457028',
    numeroFaixas: 16,
    duracao: '62:00',
    descricao:
      "Estreia de A$AP Rocky em major, com o cloud rap arrastado que definiu o som de Harlem no início dos anos 2010. A prensagem dupla importada segue a sequência original de faixas. Produções de Clams Casino e Hit-Boy sustentam o clima do disco.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 4,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-10',
    autorizacaoGerente: null,
  },
  {
    id: 2412268,
    title: "The Melodic Blue",
    artist: "Baby Keem",
    releaseYear: 2021,
    genres: ["Hip Hop"],
    styles: ["Trap", "Pop Rap"],
    price: 359,
    coverSrc: "https://i.discogs.com/-InboBpaeCX6nzm64ZqsERwVmYudimKVEd3JySjyNRY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwMTgz/OTkyLTE2Mzg5Njk0/OTEtMTUwNi5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/DoxMAay-QIgOkLBqBenaW6o8_-GBz0GF3uNDyW5SiII/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwMTgz/OTkyLTE2Mzg5Njk0/OTEtMTUwNi5qcGVn.jpeg",
    numForSale: 57,
    discogsUri: "https://www.discogs.com/master/2412268-Baby-Keem-The-Melodic-Blue",
    gravadora: "pgLang / Columbia",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem", "ed-vinil-colorido"],
    codigoCatalogo: 'MELODICBLUE-2412268',
    codigoBarras: '7891123457035',
    numeroFaixas: 16,
    duracao: '53:33',
    descricao:
      "Álbum de estreia de Baby Keem pela pgLang, com beats que trocam de direção no meio das faixas. A tiragem em vinil colorido acompanha o encarte original. As participações de Kendrick Lamar renderam ao disco um Grammy de melhor performance de rap.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 9,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-19',
    autorizacaoGerente: null,
  },
  {
    id: 3524320,
    title: "Hardstone Psycho",
    artist: "Don Toliver",
    releaseYear: 2024,
    genres: ["Hip Hop", "Rock", "Funk / Soul", "Pop"],
    styles: ["Trap", "Contemporary R&B", "Pop Rap"],
    price: 399,
    coverSrc: "https://i.discogs.com/AktnK-wqhtgp875cgkhe1vMggV9xbdkpBjrRKvLyypE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxMDQw/MDgwLTE3MjU1Njg3/MTYtNzMzOC5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/CHC76DN39sN2ymYfgS9FYAEwEgRS7cDF4KDiMEzoJkw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxMDQw/MDgwLTE3MjU1Njg3/MTYtNzMzOC5qcGVn.jpeg",
    numForSale: 68,
    discogsUri: "https://www.discogs.com/master/3524320-Don-Toliver-Hardstone-Psycho",
    gravadora: "Cactus Jack / Atlantic",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'HARDSTONE-3524320',
    codigoBarras: '7891123457042',
    numeroFaixas: 19,
    duracao: '61:40',
    descricao:
      "Quarto disco de Don Toliver puxa para o rock e o psicodélico sem largar o trap melódico da Cactus Jack. O vinil duplo traz a arte de capa em gatefold. Um dos títulos de maior giro do catálogo recente da loja.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 21,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-23',
    autorizacaoGerente: null,
  },
  {
    id: 3002207,
    title: "Love Sick",
    artist: "Don Toliver",
    releaseYear: 2023,
    genres: ["Hip Hop"],
    styles: ["Trap", "Contemporary R&B"],
    price: 349,
    coverSrc: "https://i.discogs.com/OdYegKSuCCEHHgLWdAA782n_6qwtXgzmtMrWRB-SIOw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MjA3/NDk4LTE2NzcyNzQx/MTYtOTgzMi5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/dMTw9Jogt2H83bfuk7pT1sxlK4PELFgzBfGlCCFlI84/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MjA3/NDk4LTE2NzcyNzQx/MTYtOTgzMi5qcGVn.jpeg",
    numForSale: 64,
    discogsUri: "https://www.discogs.com/master/3002207-Don-Toliver-Love-Sick",
    gravadora: "Cactus Jack / Atlantic",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'LOVESICK-3002207',
    codigoBarras: '7891123457049',
    numeroFaixas: 16,
    duracao: '52:42',
    descricao:
      "Terceiro álbum de Don Toliver, construído em torno de faixas de R&B melódico com produção espaçosa. A edição deluxe acrescenta faixas que não constam na versão padrão. Participações de Future, Justin Bieber e GloRilla completam o disco.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 7,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-14',
    autorizacaoGerente: null,
  },
  {
    id: 107391,
    title: "Blue Hawaii",
    artist: "Elvis Presley",
    releaseYear: 1961,
    genres: ["Rock", "Stage & Screen"],
    styles: ["Soundtrack", "Rock & Roll"],
    price: 219,
    coverSrc: "https://i.discogs.com/8GYH6IKk2oSttCmPfDZ_HDUJqA3aP1Mg0JtxokqXh80/rs:fit/g:sm/q:90/h:459/w:471/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNTYw/MjE0LTE1MTg1MDY5/NjUtODU5NC5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/AqZ_PJn5vcujj6scGFsBcQWrxiPDKO1DmjDBHCcfrdw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNTYw/MjE0LTE1MTg1MDY5/NjUtODU5NC5qcGVn.jpeg",
    numForSale: 2109,
    discogsUri: "https://www.discogs.com/master/107391-Elvis-Presley-Blue-Hawaii",
    gravadora: "RCA Victor",
    formatoId: 'fmt-lp',
    edicaoIds: ["ed-reprensagem", "ed-remasterizado"],
    codigoCatalogo: 'BLUEHAWAII-107391',
    codigoBarras: '7891123457056',
    numeroFaixas: 14,
    duracao: '31:49',
    descricao:
      "Trilha do filme homônimo, foi o disco mais vendido de Elvis Presley em vida e ficou vinte semanas no topo da parada americana. A remasterização preserva o timbre dos arranjos havaianos originais. Inclui Can't Help Falling In Love na sequência original.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 11,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-08',
    autorizacaoGerente: null,
  },
  {
    id: 923402,
    title: "What A Time To Be Alive",
    artist: "Drake",
    releaseYear: 2015,
    genres: ["Hip Hop"],
    styles: ["Trap", "Pop Rap"],
    price: 369,
    coverSrc: "https://i.discogs.com/ivJ9MOCeGLvq1-yPRml59ICHFNy-v_Ki0RPP4OOOKj0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1MDI1/MTMtMTQ1ODM3OTEx/My02NzI3LmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/NHVSZthOAWvmskvUHhPC5T4hLrzrkR3TzzQPNSnUfR0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1MDI1/MTMtMTQ1ODM3OTEx/My02NzI3LmpwZWc.jpeg",
    numForSale: 89,
    discogsUri: "https://www.discogs.com/master/923402-Drake-Future-4-What-A-Time-To-Be-Alive",
    gravadora: "Cash Money / Epic",
    formatoId: 'fmt-lp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'WATTBA-923402',
    codigoBarras: '7891123457063',
    numeroFaixas: 11,
    duracao: '40:30',
    descricao:
      "Mixtape colaborativa de Drake e Future gravada em menos de uma semana em Atlanta, com Metro Boomin na produção da maior parte das faixas. A prensagem importada mantém o encarte simples da edição original. Um retrato do trap que dominou 2015.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 3,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-06',
    autorizacaoGerente: null,
  },
  {
    id: 1046042,
    title: "Blonde",
    artist: "Frank Ocean",
    releaseYear: 2016,
    genres: ["Hip Hop", "Funk / Soul", "Pop"],
    styles: ["Contemporary R&B", "Psychedelic", "Neo Soul"],
    price: 459,
    coverSrc: "https://i.discogs.com/VurGdqd_vsJCl1tB9JHDfKhu5pQmKbCWSkNYnuHCFZk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5MzI1/MTQtMTc3MTczMzA2/NS01NjY2LmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/3D2NOILQzQdwR9VXWglnU2bj-sxoTi1sbT4uSltxy3E/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5MzI1/MTQtMTc3MTczMzA2/NS01NjY2LmpwZWc.jpeg",
    numForSale: 108,
    discogsUri: "https://www.discogs.com/master/1046042-Frank-Ocean-Blonde",
    gravadora: "Boys Don't Cry",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'BLONDE-1046042',
    codigoBarras: '7891123457070',
    numeroFaixas: 17,
    duracao: '60:08',
    descricao:
      "Segundo álbum de Frank Ocean troca a estrutura de canção do Channel Orange por faixas mais abertas e experimentais. As reprensagens são raras e costumam esgotar rápido, o que mantém o preço alto no mercado. Um disco central do R&B da década de 2010.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 2,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 1545493,
    title: "Huncho Jack, Jack Huncho",
    artist: "Huncho Jack",
    releaseYear: 2017,
    genres: ["Hip Hop"],
    styles: ["Trap"],
    price: 379,
    coverSrc: "https://i.discogs.com/6TxdxxjP2p7UI8LDTvF-HVj26dinC_8tJH8kf2YA26M/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMzE1/MzY3LTE1ODQxMzAy/MDUtMTc1NC5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/f4SfLUW5C6vfoLHCTE0EVtrjB__A6GAsNuuPq3Zf_pE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMzE1/MzY3LTE1ODQxMzAy/MDUtMTc1NC5qcGVn.jpeg",
    numForSale: 0,
    discogsUri: "https://www.discogs.com/master/1545493-Huncho-Jack-Travis-Scott-2-Quavo-Huncho-Jack-Jack-Huncho",
    gravadora: "Cactus Jack / Quality Control",
    formatoId: 'fmt-lp',
    edicaoIds: ["ed-primeira-prensagem", "ed-vinil-colorido"],
    codigoCatalogo: 'HUNCHOJACK-1545493',
    codigoBarras: '7891123457077',
    numeroFaixas: 13,
    duracao: '41:27',
    descricao:
      "Projeto conjunto de Travis Scott e Quavo, gravado no intervalo entre os discos solo dos dois. A prensagem importada em vinil colorido segue a arte original da Cactus Jack. Trap de produção densa, com os dois se revezando nos refrões.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 5,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-12',
    autorizacaoGerente: null,
  },
  {
    id: 767810,
    title: "2014 Forest Hills Drive",
    artist: "J. Cole",
    releaseYear: 2014,
    genres: ["Hip Hop"],
    styles: ["Conscious"],
    price: 339,
    coverSrc: "https://i.discogs.com/Dnt3OZd8WjOubOKc9tYU7KUIcEICuk8m-3jIccIo5xw/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY0MDE3/ODgtMTU1OTU4ODIx/Ni0yMjExLmpwZWc.jpeg",
    coverThumb: "https://i.discogs.com/1h_3_u7xJi59-BA0wc29j_aZv_MH9Ze--Hz7r2Ie9Y8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY0MDE3/ODgtMTU1OTU4ODIx/Ni0yMjExLmpwZWc.jpeg",
    numForSale: 317,
    discogsUri: "https://www.discogs.com/master/767810-J-Cole-2014-Forest-Hills-Drive",
    gravadora: "Dreamville / Roc Nation",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'FORESTHILLS-767810',
    codigoBarras: '7891123457084',
    numeroFaixas: 13,
    duracao: '64:39',
    descricao:
      "Terceiro disco de J. Cole, gravado sem nenhuma participação e todo produzido por ele mesmo. O título vem do endereço da casa onde cresceu, em Fayetteville. A reprensagem dupla mantém o encarte com as letras impressas.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 13,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-20',
    autorizacaoGerente: null,
  },
  {
    id: 3933725,
    title: "God Does Like Ugly",
    artist: "J.I.D",
    releaseYear: 2025,
    genres: ["Hip Hop"],
    styles: [],
    price: 389,
    coverSrc: "https://i.discogs.com/QNul47NwSkc3MsvCTuu0bf7pifIIuDQgPRqdJapPihQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0NzYy/MjM1LTE3NTQ2MDYz/NzItNTYwMi5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/zcfaOFvFQkaT7t_9PxirYfnuelE-ijZhnYh8fE-b-Mw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0NzYy/MjM1LTE3NTQ2MDYz/NzItNTYwMi5qcGVn.jpeg",
    numForSale: 100,
    discogsUri: "https://www.discogs.com/master/3933725-JID-God-Does-Like-Ugly",
    gravadora: "Dreamville / Interscope",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'UGLY-3933725',
    codigoBarras: '7891123457091',
    numeroFaixas: 15,
    duracao: '57:18',
    descricao:
      "Novo álbum de JID, ainda no giro alto das primeiras semanas de lançamento. A prensagem dupla acompanha encarte com as letras e arte de capa em gatefold. Um dos títulos mais procurados do catálogo recente da loja.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 18,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-23',
    autorizacaoGerente: null,
  },
  {
    id: 6651,
    title: "Metallica",
    artist: "Metallica",
    releaseYear: 1991,
    genres: ["Rock"],
    styles: ["Hard Rock", "Heavy Metal", "Thrash", "Groove Metal"],
    price: 329,
    coverSrc: "https://i.discogs.com/0QSPrbxUSY2NPjUj47VQ4zyAbK8S8SiAnxDnil5LPoc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4MTk4/OC0xNjIxMDEyMzY3/LTY2OTguanBlZw.jpeg",
    coverThumb: "https://i.discogs.com/MXUvXNMvpbu4GR5nzrHOKULq2i4NnLfkAET8vwqOM2U/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4MTk4/OC0xNjIxMDEyMzY3/LTY2OTguanBlZw.jpeg",
    numForSale: 2451,
    discogsUri: "https://www.discogs.com/master/6651-Metallica-Metallica",
    gravadora: "Elektra",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem", "ed-remasterizado"],
    codigoCatalogo: 'METALLICA-6651',
    codigoBarras: '7891123457098',
    numeroFaixas: 12,
    duracao: '62:16',
    descricao:
      "O disco homônimo de 1991, conhecido como Black Album, marcou a virada do Metallica para um som mais direto e de produção limpa. A remasterização em vinil duplo separa as faixas com folga de sulco, o que melhora o grave. Um dos álbuns de metal mais vendidos da história.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 17,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 1328530,
    title: "Culture II",
    artist: "Migos",
    releaseYear: 2018,
    genres: ["Hip Hop"],
    styles: ["Trap"],
    price: 479,
    coverSrc: "https://i.discogs.com/IWoWNdJMGr0WkCfk1A5a0d1n2LHtLx9ZD-mw6E6KGkY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNTk4/MDYxLTE1MzA3MTcx/NjYtNjU3NS5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/IKt3ozkyQgT2F-DgZ-8RZzJlN1R4wZAPXlXsHFMAcdw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNTk4/MDYxLTE1MzA3MTcx/NjYtNjU3NS5qcGVn.jpeg",
    numForSale: 58,
    discogsUri: "https://www.discogs.com/master/1328530-Migos-Culture-II",
    gravadora: "Quality Control / Motown",
    formatoId: 'fmt-3xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'CULTURE2-1328530',
    codigoBarras: '7891123457105',
    numeroFaixas: 24,
    duracao: '105:02',
    descricao:
      "Sequência de Culture com vinte e quatro faixas, o que exigiu prensagem tripla para caber sem perder qualidade de áudio. Produções de Metro Boomin, Pharrell e Kanye West se alternam ao longo do disco. Um retrato do auge comercial do trio de Atlanta.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.5,
      peso: 700,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 3,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-05',
    autorizacaoGerente: null,
  },
  {
    id: 2057692,
    title: "Whole Lotta Red",
    artist: "Playboi Carti",
    releaseYear: 2020,
    genres: ["Hip Hop"],
    styles: ["Trap"],
    price: 429,
    coverSrc: "https://i.discogs.com/R__ClQV_qnaV0ITzx0pwkzZfcdbC5F4E5MyTUNaf7TU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2NjE4/MzE3LTE2MTAyODEy/NzUtODcyMy5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/f4wUaaM_Pl4iunqVYd0gkPhSxts7NyeFPr9Ur0sUWpg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2NjE4/MzE3LTE2MTAyODEy/NzUtODcyMy5qcGVn.jpeg",
    numForSale: 204,
    discogsUri: "https://www.discogs.com/master/2057692-Playboi-Carti-Whole-Lotta-Red",
    gravadora: "AWGE / Interscope",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem", "ed-vinil-colorido"],
    codigoCatalogo: 'WLR-2057692',
    codigoBarras: '7891123457119',
    numeroFaixas: 24,
    duracao: '63:13',
    descricao:
      "Terceiro disco de Playboi Carti, de recepção dividida no lançamento e hoje tratado como divisor de águas do rage. A tiragem em vinil colorido importado costuma sumir rápido do mercado. Produções de F1lthy e Pi'erre Bourne sustentam o clima distorcido.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 4,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-17',
    autorizacaoGerente: null,
  },
  {
    id: 2929684,
    title: "SOS",
    artist: "SZA",
    releaseYear: 2022,
    genres: ["Funk / Soul"],
    styles: ["Contemporary R&B"],
    price: 369,
    coverSrc: "https://i.discogs.com/7hutaiit_yV70u-gZbn5qQw6lx7PzWVixKYuk8FI15U/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NDA0/MjgzLTE2NzA1MDY1/MjctNTcwMS5wbmc.jpeg",
    coverThumb: "https://i.discogs.com/Q3mdNFaMWltMOeA_2GeWnUoZDM1hY72bjgnbrEB3mFE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NDA0/MjgzLTE2NzA1MDY1/MjctNTcwMS5wbmc.jpeg",
    numForSale: 339,
    discogsUri: "https://www.discogs.com/master/2929684-SZA-2-SOS",
    gravadora: "Top Dawg / RCA",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'SOS-2929684',
    codigoBarras: '7891123457126',
    numeroFaixas: 23,
    duracao: '67:49',
    descricao:
      "Segundo álbum de SZA passeia entre R&B, pop e até punk em vinte e três faixas, sem se prender a um formato. O vinil duplo acompanha o encarte com a foto do píer que virou capa. Ficou dez semanas no topo da parada americana.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 14,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 3184197,
    title: "Utopia",
    artist: "Travis Scott",
    releaseYear: 2023,
    genres: ["Electronic", "Hip Hop"],
    styles: ["Trap", "Cloud Rap", "Pop Rap", "Psychedelic", "Experimental"],
    price: 409,
    coverSrc: "https://i.discogs.com/hywp7Zxb-tOP9ievyyBpeV_5NHIGRhwgnKRzU7HCyyg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3ODA4/MzE3LTE2OTA1NjM4/NTUtMTI2OC5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/QkQfOLN-nGJfGjmCjcdgp07QYhtozLJ-IOuFGURqhD0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3ODA4/MzE3LTE2OTA1NjM4/NTUtMTI2OC5qcGVn.jpeg",
    numForSale: 505,
    discogsUri: "https://www.discogs.com/master/3184197-Travis-Scott-2-Utopia",
    gravadora: "Cactus Jack / Epic",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-primeira-prensagem"],
    codigoCatalogo: 'UTOPIA-3184197',
    codigoBarras: '7891123457133',
    numeroFaixas: 19,
    duracao: '73:27',
    descricao:
      "Quarto disco de Travis Scott, construído com produção industrial e participações que vão de Beyoncé a Playboi Carti. A prensagem dupla mantém a arte de capa em gatefold. Um dos lançamentos de maior procura desde Astroworld.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 16,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-23',
    autorizacaoGerente: null,
  },
  {
    id: 1694319,
    title: "So Much Fun",
    artist: "Young Thug",
    releaseYear: 2019,
    genres: ["Hip Hop"],
    styles: ["Trap", "Pop Rap"],
    price: 319,
    coverSrc: "https://i.discogs.com/ZukeVRkVF3kAuetFwCfb_Nvu44eM3H8nvwE-UFCV848/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDQ1/MzIxLTE1OTg1MzUy/NTQtOTM3My5qcGVn.jpeg",
    coverThumb: "https://i.discogs.com/lTon4xoRuLAn8eh22D7XTpzmqNp7pA9_w-sVx_8Q2bs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDQ1/MzIxLTE1OTg1MzUy/NTQtOTM3My5qcGVn.jpeg",
    numForSale: 11,
    discogsUri: "https://www.discogs.com/master/1694319-Young-Thug-2-So-Much-Fun",
    gravadora: "300 Entertainment / YSL",
    formatoId: 'fmt-2xlp',
    edicaoIds: ["ed-reprensagem"],
    codigoCatalogo: 'SOMUCHFUN-1694319',
    codigoBarras: '7891123457140',
    numeroFaixas: 19,
    duracao: '62:13',
    descricao:
      "Primeiro álbum de estúdio oficial de Young Thug depois de anos de mixtapes, com dezenove faixas de trap melódico. A reprensagem dupla segue a sequência original. Participações de Future, Lil Uzi Vert e Gunna marcam o disco.",
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1.0,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 8,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-11',
    autorizacaoGerente: null,
  },
];
