import type { Disco } from '../types/disco';

/**
 * Dados reais do Discogs, colhidos em 21/08/2026 do endpoint público
 * /masters/{id} da API (sem autenticação). `id` é o master_id do Discogs e
 * `numForSale` é a contagem real de cópias no marketplace.
 *
 * Exceção: o good kid deluxe não existe como master no Discogs, só como
 * release dentro do master 484590. Essa entrada aponta para o release
 * 3975953 (2xLP, US, 2012) — daí o `id` ser release_id, a `discogsUri` ser
 * /release/ em vez de /master/, e o `numForSale` contar só essa prensagem
 * (70) em vez do total do master (683). O sufixo '(Deluxe Edition)' no
 * título foi acrescentado por nós: no Discogs isso vive em formats, não no
 * título, e sem ele o card fica idêntico ao da edição padrão.
 *
 * `price` é o único campo fictício: o Discogs expõe apenas lowest_price em
 * USD, que reflete cópias usadas e não um preço de varejo brasileiro.
 *
 * Títulos, artistas e gêneros seguem a grafia do Discogs ('Damn', 'Michael'),
 * exceto o sufixo de homônimo do banco deles ('Travis Scott (2)'), removido.
 * `styles` pode vir vazio (o Discogs não classificou), daí o fallback para
 * `genres` no VinylCarousel.
 *
 * `coverSrc` aponta para public/images/capas nos 11 álbuns que já tinham
 * arquivo local, e para i.discogs.com nos 13 demais. Essas URLs são
 * assinadas: se um dia pararem de responder, é sinal de baixar as imagens.
 *
 * Os campos de cadastro (gravadora, edição, códigos, dimensões, descrição...)
 * são fictícios mas plausíveis — ao contrário dos dados acima, que vieram do
 * Discogs, esses foram inventados por nós só para satisfazer a RN0011. Já
 * grupoPrecificacaoId e estoque não vêm de API nenhuma: seguem a regra de
 * negócio (RN0013) e foram distribuídos à mão para deixar a RF0013 e a
 * RN0014 demonstráveis na tela.
 */
export const discosMock: Disco[] = [
  {
    id: 1435589,
    title: 'Astroworld',
    artist: 'Travis Scott',
    releaseYear: 2018,
    genres: ['Hip Hop'],
    styles: ['Trap', 'Pop Rap', 'Psychedelic'],
    price: 389,
    coverSrc: '/images/capas/astroworld.jpg',
    numForSale: 408,
    discogsUri: 'https://www.discogs.com/master/1435589-Travis-Scott-2-Astroworld',
    gravadora: 'Cactus Jack / Epic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'EPIC-19075871371',
    codigoBarras: '7891123456781',
    numeroFaixas: 17,
    duracao: '59:21',
    descricao:
      'Álbum conceitual de Travis Scott inspirado no parque de diversões Six Flags AstroWorld, fechado em Houston. A prensagem em vinil duplo preserva a variação de clima entre as faixas, do trap mais pesado aos interlúdios psicodélicos. Participações de Drake, Frank Ocean e The Weeknd completam o encarte.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 14,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-19',
    autorizacaoGerente: null,
  },
  {
    id: 861083,
    title: 'Currents',
    artist: 'Tame Impala',
    releaseYear: 2015,
    genres: ['Electronic', 'Rock'],
    styles: ['Psychedelic Rock', 'Indie Rock'],
    price: 349,
    coverSrc: '/images/capas/currents.jpg',
    numForSale: 478,
    discogsUri: 'https://www.discogs.com/master/861083-Tame-Impala-Currents',
    gravadora: 'Modular Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'MODVL105',
    codigoBarras: '7891123456798',
    numeroFaixas: 13,
    duracao: '51:04',
    descricao:
      'Terceiro disco do Tame Impala marca a virada de Kevin Parker para produções mais eletrônicas, sem abandonar as raízes psicodélicas da banda. A sequência de faixas foi pensada para ouvir do início ao fim, e o vinil em 180g reforça essa proposta de audição contínua. Uma referência do indie rock dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 320,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 9,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 8883,
    title: 'Thriller',
    artist: 'Michael Jackson',
    releaseYear: 1982,
    genres: ['Funk / Soul', 'Pop'],
    styles: ['Contemporary R&B', 'Disco', 'Soul'],
    price: 229,
    coverSrc: '/images/capas/thriller.jpg',
    numForSale: 5029,
    discogsUri: 'https://www.discogs.com/master/8883-Michael-Jackson-Thriller',
    gravadora: 'Epic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-picture-disc', 'ed-reprensagem'],
    codigoCatalogo: 'EPIC-38112',
    codigoBarras: '7891123456804',
    numeroFaixas: 9,
    duracao: '42:19',
    descricao:
      'O disco mais vendido da história do pop, com produção de Quincy Jones e faixas que ainda tocam em pistas de dança até hoje. Esta prensagem reproduz o layout original de capa e encarte da Epic. Um item essencial para qualquer coleção que passe por Michael Jackson.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 250,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 22,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 810214,
    title: 'To Pimp A Butterfly',
    artist: 'Kendrick Lamar',
    releaseYear: 2015,
    genres: ['Hip Hop', 'Jazz', 'Funk / Soul'],
    styles: ['Conscious', 'Jazzy Hip-Hop', 'G-Funk', 'Neo Soul'],
    price: 369,
    coverSrc: '/images/capas/tpab.jpg',
    numForSale: 754,
    discogsUri: 'https://www.discogs.com/master/810214-Kendrick-Lamar-To-Pimp-A-Butterfly',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0002-LP',
    codigoBarras: '7891123456811',
    numeroFaixas: 16,
    duracao: '78:51',
    descricao:
      'Kendrick Lamar mistura jazz, funk e spoken word numa obra densa sobre raça e identidade nos Estados Unidos. A duração estendida das faixas pede o formato duplo, com gatefold que traz as letras impressas. Um dos discos mais discutidos do hip hop na década de 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 470,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 11,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-18',
    autorizacaoGerente: null,
  },
  {
    id: 10362,
    title: 'The Dark Side Of The Moon',
    artist: 'Pink Floyd',
    releaseYear: 1973,
    genres: ['Rock'],
    styles: ['Prog Rock', 'Psychedelic Rock'],
    price: 299,
    coverSrc: '/images/capas/thedarksideofthemoon.jpg',
    numForSale: 8376,
    discogsUri: 'https://www.discogs.com/master/10362-Pink-Floyd-The-Dark-Side-Of-The-Moon',
    gravadora: 'Harvest / EMI',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-remasterizado'],
    codigoCatalogo: 'HAR-SHVL804',
    codigoBarras: '7891123456828',
    numeroFaixas: 10,
    duracao: '42:59',
    descricao:
      'Um dos discos mais ouvidos do rock progressivo, gravado pelo Pink Floyd nos estúdios Abbey Road. A remasterização preservada nesta prensagem mantém a dinâmica original entre os efeitos sonoros e os instrumentos. Peça central para quem estuda a história do álbum conceitual.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 18,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-20',
    autorizacaoGerente: null,
  },
  {
    id: 6440,
    title: 'Ride The Lightning',
    artist: 'Metallica',
    releaseYear: 1984,
    genres: ['Rock'],
    styles: ['Thrash', 'Speed Metal'],
    price: 259,
    coverSrc: '/images/capas/ridethelightning.jpg',
    numForSale: 1891,
    discogsUri: 'https://www.discogs.com/master/6440-Metallica-Ride-The-Lightning',
    gravadora: 'Elektra',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'ELK-60396',
    codigoBarras: '7891123456835',
    numeroFaixas: 8,
    duracao: '46:58',
    descricao:
      'Segundo disco do Metallica, ainda dentro do thrash metal mais cru da banda antes do estouro comercial. A prensagem nacional segue o encarte clássico da Elektra, sem alterações de faixa. Recomendado para quem busca o metal oitentista em sua forma mais direta.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-classico',
    estoque: 7,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-12',
    autorizacaoGerente: null,
  },
  {
    id: 593987,
    title: 'AM',
    artist: 'Arctic Monkeys',
    releaseYear: 2013,
    genres: ['Rock'],
    styles: ['Alternative Rock', 'Indie Rock'],
    price: 279,
    coverSrc: '/images/capas/am.jpg',
    numForSale: 661,
    discogsUri: 'https://www.discogs.com/master/593987-Arctic-Monkeys-AM',
    gravadora: 'Domino Recording Co.',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'DOM-WIGLP314',
    codigoBarras: '7891123456842',
    numeroFaixas: 12,
    duracao: '40:56',
    descricao:
      'Quinto álbum do Arctic Monkeys aposta em riffs mais lentos e um clima noturno que se afastou do indie rock dos primeiros discos da banda. A cor do vinil varia entre as tiragens, mas a faixa e a masterização seguem o mesmo padrão. Um disco que ajudou a definir o som da banda na década seguinte.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 16,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 35665,
    title: 'Mezmerize',
    artist: 'System Of A Down',
    releaseYear: 2005,
    genres: ['Rock'],
    styles: ['Alternative Metal', 'Avantgarde'],
    price: 239,
    coverSrc: '/images/capas/mezmerize.jpg',
    numForSale: 547,
    discogsUri: 'https://www.discogs.com/master/35665-System-Of-A-Down-Mezmerize',
    gravadora: 'American Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem', 'ed-remasterizado'],
    codigoCatalogo: 'AMR-0602547',
    codigoBarras: '7891123456859',
    numeroFaixas: 11,
    duracao: '35:39',
    descricao:
      'Quarto disco do System Of A Down, gravado junto com o Hypnotize numa mesma sessão de estúdio. A prensagem reedição de 2017 manteve o encarte original com as letras de Serj Tankian e Daron Malakian. Um retrato do metal alternativo do início dos anos 2000.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 250,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 0,
    isAtivo: false,
    motivoStatus: {
      categoria: 'BAIXA DEMANDA',
      justificativa:
        'Giro baixo nos últimos meses; prioridade de espaço para títulos com mais saída.',
      data: '2026-02-02',
      automatico: false,
    },
    ultimaVendaEm: '2026-01-27',
    autorizacaoGerente: null,
  },
  {
    id: 1112335,
    title: 'Awaken, My Love!',
    artist: 'Childish Gambino',
    releaseYear: 2016,
    genres: ['Funk / Soul'],
    styles: ['Contemporary R&B', 'Funk', 'Neo Soul', 'Psychedelic'],
    price: 319,
    coverSrc: '/images/capas/awakenmylove.jpg',
    numForSale: 266,
    discogsUri: 'https://www.discogs.com/master/1112335-Childish-Gambino-Awaken-My-Love',
    gravadora: 'Glassnote Records',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'GLS-2521',
    codigoBarras: '7891123456866',
    numeroFaixas: 11,
    duracao: '57:57',
    descricao:
      'Childish Gambino troca o rap dos discos anteriores por funk e soul psicodélico, numa homenagem clara a Funkadelic. O encarte gatefold do vinil duplo traz o mesmo clima visual da capa, com Donald Glover em tons esverdeados. Um disco que surpreendeu quem esperava outro álbum de hip hop.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.9,
      peso: 460,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 5,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-09',
    autorizacaoGerente: null,
  },
  {
    id: 950545,
    title: 'Anti',
    artist: 'Rihanna',
    releaseYear: 2016,
    genres: ['Hip Hop', 'Pop'],
    styles: ['Contemporary R&B', 'Soul'],
    price: 359,
    coverSrc: '/images/capas/anti.jpg',
    numForSale: 238,
    discogsUri: 'https://www.discogs.com/master/950545-Rihanna-Anti',
    gravadora: 'Westbury Road Entertainment',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'WBR-2016-LP',
    codigoBarras: '0602557193281',
    numeroFaixas: 13,
    duracao: '43:50',
    descricao:
      'Rihanna abandona as fórmulas de hit single para um disco mais introspectivo, gravado ao longo de anos de sessões dispersas. A prensagem em vinil translúcido acompanha o encarte com as letras completas. Um ponto de virada na carreira da artista.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 4,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-07-30',
    autorizacaoGerente: 'Rodrigo Rocha — 12/07/2026',
  },
  {
    id: 1164779,
    title: 'Damn',
    artist: 'Kendrick Lamar',
    releaseYear: 2017,
    genres: ['Hip Hop', 'Funk / Soul'],
    styles: ['Conscious', 'Contemporary R&B', 'Jazzy Hip-Hop', 'Trap', 'Boom Bap'],
    price: 339,
    coverSrc: '/images/capas/damn.jpg',
    numForSale: 607,
    discogsUri: 'https://www.discogs.com/master/1164779-Kendrick-Lamar-Damn',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0006-LP',
    codigoBarras: '7891123456873',
    numeroFaixas: 14,
    duracao: '54:54',
    descricao:
      'Kendrick Lamar alterna faixas de contemplação religiosa com produções mais diretas para rádio, num disco que rendeu o Pulitzer de música. A capa reversível desta prensagem permite trocar entre o título em preto e em vermelho. Um marco do hip hop consciente da década.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 13,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-21',
    autorizacaoGerente: null,
  },
  {
    id: 1473270,
    title: 'Not All Heroes Wear Capes',
    artist: 'Metro Boomin',
    releaseYear: 2018,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 359,
    coverSrc: 'https://i.discogs.com/Jqu3KIN38JhzhDbC97NzhZ9e-tlFZ8R7v9ZD9UVe-co/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyMjc2/NDQxLTE2NDU2MzU1/MzAtOTE4Mi5qcGVn.jpeg',
    numForSale: 52,
    discogsUri: 'https://www.discogs.com/master/1473270-Metro-Boomin-Not-All-Heroes-Wear-Capes',
    gravadora: 'Boominati Worldwide',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'BMW-71234',
    codigoBarras: '0060254712349',
    numeroFaixas: 12,
    duracao: '44:18',
    descricao:
      'Primeiro álbum solo de Metro Boomin reúne parceiros de longa data como 21 Savage, Travis Scott e Kodak Black sob sua produção característica. A prensagem importada segue o encarte simples da edição americana. Um retrato do trap de produtor que marcou o final dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 3,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-05',
    autorizacaoGerente: null,
  },
  {
    id: 1085420,
    title: 'Birds In The Trap Sing McKnight',
    artist: 'Travis Scott',
    releaseYear: 2016,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 369,
    coverSrc: 'https://i.discogs.com/awwmHLs5RtRYcnFH5FcIe9WN4MPgpoegnJEBXWdBR0E/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5ODky/OTgtMTU0OTA1MzE4/NS0yNzE0LmpwZWc.jpeg',
    numForSale: 267,
    discogsUri: 'https://www.discogs.com/master/1085420-Travis-Scott-2-Birds-In-The-Trap-Sing-McKnight',
    gravadora: 'Grand Hustle / Epic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'EPIC-B12016LP',
    codigoBarras: '0886985031382',
    numeroFaixas: 14,
    duracao: '48:32',
    descricao:
      'Segundo álbum de estúdio de Travis Scott, com produção que mistura trap e texturas psicodélicas mais experimentais que o disco de estreia. A cor do vinil varia entre as tiragens importadas, mas a faixa segue o encarte original. Participações de Kendrick Lamar e André 3000 completam o disco.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 280,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-02-10',
    autorizacaoGerente: null,
  },
  {
    id: 4119973,
    title: 'Octane',
    artist: 'Don Toliver',
    releaseYear: 2026,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 329,
    coverSrc: 'https://i.discogs.com/Uws6X_YtdeyigTLt0zdApEfE2gdJxuBDVgMyHvsNcu8/rs:fit/g:sm/q:90/h:592/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NTI1/MDY0LTE3NzEyNzM3/MjMtNzg0OS5wbmc.jpeg',
    numForSale: 109,
    discogsUri: 'https://www.discogs.com/master/4119973-Don-Toliver-Octane',
    gravadora: 'Cactus Jack / Atlantic',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'ATL-2026114',
    codigoBarras: '7891123456880',
    numeroFaixas: 15,
    duracao: '52:10',
    descricao:
      'Novo álbum de Don Toliver, ainda no giro alto de vendas típico das primeiras semanas de lançamento. A prensagem simples em vinil acompanha um encarte numerado, próprio das primeiras tiragens. Um disco recente que já figura entre os mais buscados da loja.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 25,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-23',
    autorizacaoGerente: null,
  },
  {
    id: 8497,
    title: 'Graduation',
    artist: 'Kanye West',
    releaseYear: 2007,
    genres: ['Hip Hop', 'Funk / Soul'],
    styles: ['Contemporary R&B', 'Pop Rap'],
    price: 309,
    coverSrc: 'https://i.discogs.com/ZGCZsgTZlSxAbspOky80WD6jI_tc6zoJuXfqZAEWYkI/rs:fit/g:sm/q:90/h:537/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNjY2/MDEtMTYzMjU2Nzcx/Mi0xNTg2LnBuZw.jpeg',
    numForSale: 167,
    discogsUri: 'https://www.discogs.com/master/8497-kanYeWest-Graduation',
    gravadora: 'Roc-A-Fella / Def Jam',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'DEF-0601811',
    codigoBarras: '7891123456897',
    numeroFaixas: 13,
    duracao: '52:09',
    descricao:
      'Terceiro disco de Kanye West marca a virada do rapper para produções mais eletrônicas e influenciadas por rock de estádios. O gatefold desta reedição traz as ilustrações de Takashi Murakami usadas na capa original. Um divisor de águas entre o Kanye de Late Registration e a fase mais pop dos discos seguintes.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.6,
      peso: 320,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 8,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-17',
    autorizacaoGerente: null,
  },
  {
    id: 2670629,
    title: 'Un Verano Sin Ti',
    artist: 'Bad Bunny',
    releaseYear: 2022,
    genres: ['Electronic', 'Hip Hop', 'Reggae', 'Latin', 'Pop'],
    styles: ['Reggaeton', 'Trap', 'Synth-pop', 'House', 'Reggae', 'Mambo', 'Latin Pop'],
    price: 399,
    coverSrc: 'https://i.discogs.com/AVfnmTckGhWNpTOluDOLMqAXo-lwDuK8RK-zRw7DjUo/rs:fit/g:sm/q:90/h:528/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MTEy/NTIwLTE2NjE2NTUx/ODQtMTg3NC5qcGVn.jpeg',
    numForSale: 3,
    discogsUri: 'https://www.discogs.com/master/2670629-Bad-Bunny-Un-Verano-Sin-Ti',
    gravadora: 'Rimas Entertainment',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'RIM-2022UVST',
    codigoBarras: '6061234567892',
    numeroFaixas: 23,
    duracao: '81:14',
    descricao:
      'Bad Bunny expande o reggaeton para o pop e para ritmos caribenhos como bomba e plena, num disco que dominou as paradas globais. A prensagem em vinil duplo importado segue o gatefold da edição internacional. Ainda sem saída de estoque nesta loja, apesar da procura constante pelo título.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: null,
    autorizacaoGerente: null,
  },
  {
    id: 883244,
    title: 'Rodeo',
    artist: 'Travis Scott',
    releaseYear: 2015,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 379,
    coverSrc: 'https://i.discogs.com/IvgsheLssaAfZNjFGiQK1k59Hzw4NYJ6F_sackrd9H0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNjAz/MDI4LTE3MzQ1NTQ0/NDEtOTQ2NC5wbmc.jpeg',
    numForSale: 232,
    discogsUri: 'https://www.discogs.com/master/883244-Travis-Scott-2-Rodeo',
    gravadora: 'Grand Hustle / Epic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'EPIC-R15LP2',
    codigoBarras: '0889854021479',
    numeroFaixas: 14,
    duracao: '65:57',
    descricao:
      'Álbum de estreia de Travis Scott, com produção que aproxima trap e rock psicodélico, num som que o artista aprofundaria nos discos seguintes. A tiragem importada em vinil colorido segue o encarte duplo original. Participações de Kanye West, Toro y Moi e The Weeknd marcam a lista de faixas.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 490,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 6,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-14',
    autorizacaoGerente: null,
  },
  {
    id: 4155436,
    title: 'Thy Will Be Done',
    artist: '$uicideboy$',
    releaseYear: 2026,
    genres: ['Hip Hop'],
    styles: ['Hardcore Hip-Hop', 'Trap', 'Cloud Rap'],
    price: 299,
    coverSrc: 'https://i.discogs.com/p2KgWoTCRME4SVR6vq1Q6G1ULgDSnaj3KOmOOKP0QQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2Njk2/Nzk5LTE3NzMwOTM1/MjMtNjcwNi5qcGVn.jpeg',
    numForSale: 120,
    discogsUri: 'https://www.discogs.com/master/4155436-uicideboy-Thy-Will-Be-Done',
    gravadora: 'G59 Records',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'G59-2026TWBD',
    codigoBarras: '7891123456903',
    numeroFaixas: 12,
    duracao: '38:24',
    descricao:
      'Novo lançamento do duo $uicideboy$, que segue na linha de horrorcore e trap sombrio construída desde os primeiros mixtapes do grupo. A tiragem em vinil colorido numerado esgotou rápido nesta loja, ainda no mês de lançamento. Uma prensagem de tiragem limitada, sem previsão de reposição.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.4,
      peso: 260,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 0,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-19',
    autorizacaoGerente: null,
  },
  {
    id: 3716847,
    title: 'Debí Tirar Más Fotos',
    artist: 'Bad Bunny',
    releaseYear: 2025,
    genres: ['Electronic', 'Hip Hop', 'Latin', 'Pop'],
    styles: ['Reggaeton', 'Salsa', 'Aguinaldo', 'Bomba', 'Plena', 'Trap', 'Hip Hop', 'House', 'Latin Pop'],
    price: 389,
    coverSrc: 'https://i.discogs.com/sKdg2-UawQ7QzMOqg7VXpJktykbjEloglXcmb-4jk1E/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyODE3/NDAyLTE3MzY2MjA3/NTctMzY3Ni5qcGVn.jpeg',
    numForSale: 319,
    discogsUri: 'https://www.discogs.com/master/3716847-Bad-Bunny-Debí-Tirar-Más-Fotos',
    gravadora: 'Rimas Entertainment',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'RIM-2025DTMF',
    codigoBarras: '7891123456910',
    numeroFaixas: 17,
    duracao: '52:16',
    descricao:
      'Bad Bunny retorna às raízes porto-riquenhas com um disco que passeia por salsa, plena e reggaeton clássico. A prensagem de lançamento traz um encarte com fotos do processo de gravação. Um dos títulos mais procurados do catálogo latino da loja.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 300,
    },
    grupoPrecificacaoId: 'gp-lancamento',
    estoque: 19,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-22',
    autorizacaoGerente: null,
  },
  {
    id: 288153,
    title: 'My Beautiful Dark Twisted Fantasy',
    artist: 'Kanye West',
    releaseYear: 2010,
    genres: ['Hip Hop'],
    styles: ['Pop Rap', 'Contemporary R&B'],
    price: 429,
    coverSrc: 'https://i.discogs.com/3RRJgAX-aSq0JB4tAZBpdWQezFQPiDauBE9eV0uhEAM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTkx/NTItMTczMTcxMzky/OC01OTQ0LmpwZWc.jpeg',
    numForSale: 459,
    discogsUri: 'https://www.discogs.com/master/288153-Kanye-West-My-Beautiful-Dark-Twisted-Fantasy',
    gravadora: 'GOOD Music / Def Jam',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem'],
    codigoCatalogo: 'GOOD-0602527',
    codigoBarras: '0602527730951',
    numeroFaixas: 13,
    duracao: '68:23',
    descricao:
      'Quinto disco de Kanye West é considerado por muita gente o ápice de sua fase de produção mais orquestral e maximalista. A prensagem importada em vinil duplo mantém o gatefold com a arte de George Condo. Participações de Rick Ross, Nicki Minaj e Bon Iver reforçam o caráter coletivo do projeto.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 500,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 2,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-16',
    autorizacaoGerente: null,
  },
  {
    id: 454284,
    title: 'Channel Orange',
    artist: 'Frank Ocean',
    releaseYear: 2012,
    genres: ['Hip Hop', 'Funk / Soul', 'Pop'],
    styles: ['Contemporary R&B', 'Soul', 'Neo Soul'],
    price: 419,
    coverSrc: 'https://i.discogs.com/T194rRO-vNdN71vM_XUorDW2B3kNN5X4EwFDweUtDlc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MzEx/ODUtMTc0NTQ0NzIy/Ni05NTIzLmpwZWc.jpeg',
    numForSale: 255,
    discogsUri: 'https://www.discogs.com/master/454284-Frank-Ocean-Channel-Orange',
    gravadora: 'Def Jam Recordings',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-reprensagem', 'ed-vinil-colorido'],
    codigoCatalogo: 'DEF-0602537',
    codigoBarras: '0602537123457',
    numeroFaixas: 17,
    duracao: '62:29',
    descricao:
      'Álbum de estreia de Frank Ocean fora do coletivo Odd Future, com um R&B mais introspectivo e cheio de interlúdios narrativos. A prensagem importada em vinil duplo colorido segue o layout original de faixas. Um disco que ajudou a redefinir o R&B contemporâneo dos anos 2010.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 470,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 5,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-13',
    autorizacaoGerente: null,
  },
  {
    id: 3975953,
    title: 'Good Kid, M.A.A.D City (Deluxe Edition)',
    artist: 'Kendrick Lamar',
    releaseYear: 2012,
    genres: ['Hip Hop'],
    styles: ['Conscious'],
    price: 419,
    coverSrc: 'https://i.discogs.com/m8eUFdh6Dmu3VIwfNJUNI8Eht0dZfJyB9ycEYgatQdY/rs:fit/g:sm/q:90/h:588/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5NzU5/NTMtMTU3MDQwNDc5/NS01Njk0LmpwZWc.jpeg',
    numForSale: 70,
    discogsUri: 'https://www.discogs.com/release/3975953-Kendrick-Lamar-Good-Kid-MAAD-City',
    gravadora: 'Top Dawg Entertainment / Interscope',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'TDE-0001-LP-DX',
    codigoBarras: '0602537891234',
    numeroFaixas: 15,
    duracao: '78:53',
    descricao:
      'Edição estendida do álbum de estreia de Kendrick Lamar pela major, com faixas bônus que não constam na versão padrão. A prensagem importada em vinil duplo já não é mais fabricada, o que a torna uma das poucas formas físicas de acessar essas faixas extras. Um documento da chegada de Kendrick ao mainstream.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 500,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 0,
    isAtivo: false,
    motivoStatus: {
      categoria: 'FORA DE LINHA',
      justificativa:
        'Edição deluxe saiu de linha do fornecedor, sem previsão de nova prensagem.',
      data: '2025-12-10',
      automatico: false,
    },
    ultimaVendaEm: '2025-11-04',
    autorizacaoGerente: null,
  },
  {
    id: 3227581,
    title: 'Michael',
    artist: 'Killer Mike',
    releaseYear: 2023,
    genres: ['Hip Hop'],
    styles: [],
    price: 319,
    coverSrc: 'https://i.discogs.com/HjSnYQqDpXzsptDgtitRJVoqP-xUm8dWmSeEMMWIq34/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NDAz/MTk0LTE2ODY5NDc2/NDAtODE2MC5qcGVn.jpeg',
    numForSale: 172,
    discogsUri: 'https://www.discogs.com/master/3227581-Killer-Mike-Michael',
    gravadora: 'Loma Vista Recordings',
    formatoId: 'fmt-lp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'LOMA-23018',
    codigoBarras: '7891123456927',
    numeroFaixas: 14,
    duracao: '53:33',
    descricao:
      'Disco de Killer Mike depois do sucesso do Run The Jewels, com produção que dialoga com gospel e soul do sul dos Estados Unidos. A reedição em 180g mantém o encarte original com participações de André 3000 e Future. Um retorno ao trabalho solo que rendeu ao rapper o Grammy de melhor álbum de rap.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 0.5,
      peso: 290,
    },
    grupoPrecificacaoId: 'gp-catalogo',
    estoque: 10,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-11',
    autorizacaoGerente: null,
  },
  {
    id: 2890219,
    title: 'Heroes & Villains',
    artist: 'Metro Boomin',
    releaseYear: 2022,
    genres: ['Hip Hop'],
    styles: ['Trap'],
    price: 369,
    coverSrc: 'https://i.discogs.com/n21h0GO52Iw6d_vhdqXdAi3H5jlkSBf8kp4yYsaVDaU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1MzUx/MDIxLTE3NTQwMDEz/NjgtNTExMS5qcGVn.jpeg',
    numForSale: 109,
    discogsUri: 'https://www.discogs.com/master/2890219-Metro-Boomin-Heroes-Villains',
    gravadora: 'Boominati Worldwide / Republic',
    formatoId: 'fmt-2xlp',
    edicaoIds: ['ed-primeira-prensagem'],
    codigoCatalogo: 'BMW-22HV002',
    codigoBarras: '0060254789013',
    numeroFaixas: 15,
    duracao: '53:57',
    descricao:
      'Segundo álbum solo de Metro Boomin, com uma lista de participações que passa por Travis Scott, Future e The Weeknd. A prensagem importada em vinil duplo mantém o gatefold da edição americana. Um disco que consolidou o produtor como nome de peso fora dos créditos de estúdio.',
    dimensoes: {
      altura: 31.5,
      largura: 31.5,
      profundidade: 1,
      peso: 480,
    },
    grupoPrecificacaoId: 'gp-importado',
    estoque: 7,
    isAtivo: true,
    motivoStatus: null,
    ultimaVendaEm: '2026-08-20',
    autorizacaoGerente: null,
  },
];

// Recortes para as seções da home
export const discosEmAlta: Disco[] = discosMock;

export const discosMaisVendidos: Disco[] = [...discosMock].sort(
  (a, b) => b.numForSale - a.numForSale,
);

export const discosNovidades: Disco[] = [...discosMock].sort(
  (a, b) => b.releaseYear - a.releaseYear,
);
