import type { Faixa } from '../types/disco';

/**
 * Tracklists colhidas do endpoint /masters (ou /releases, no good kid deluxe) do
 * Discogs em 24/08/2026, indexadas por id de disco. Quando o master vem sem
 * duração, ela sai de outra edição do mesmo master, casada pelo título da faixa.
 *
 * Ficam fora de discosMock de propósito: são 663 linhas que só a página do disco
 * consome, e misturá-las ao catálogo tornaria o mock difícil de ler. Disco
 * cadastrado à mão no admin simplesmente não aparece aqui — a tela cai no
 * numeroFaixas, que é o que a RN0011 exige.
 */
export const faixasPorDisco: Record<number, Faixa[]> = {
  1435589: [
    { posicao: "1", titulo: "Stargazing", duracao: "4:30" },
    { posicao: "2", titulo: "Carousel", duracao: "3:00" },
    { posicao: "3", titulo: "Sicko Mode", duracao: "5:12" },
    { posicao: "4", titulo: "R.I.P Screw", duracao: "3:05" },
    { posicao: "5", titulo: "Stop Trying To Be God", duracao: "5:38" },
    { posicao: "6", titulo: "No Bystanders", duracao: "3:38" },
    { posicao: "7", titulo: "Skeletons", duracao: "2:25" },
    { posicao: "8", titulo: "Wake Up", duracao: "3:51" },
    { posicao: "9", titulo: "5% Tint", duracao: "3:16" },
    { posicao: "10", titulo: "NC-17", duracao: "2:36" },
    { posicao: "11", titulo: "Astrothunder", duracao: "2:22" },
    { posicao: "12", titulo: "Yosemite", duracao: "2:30" },
    { posicao: "13", titulo: "Can't Say", duracao: "3:18" },
    { posicao: "14", titulo: "Who? What!", duracao: "2:56" },
    { posicao: "15", titulo: "Butterfly Effect", duracao: "3:10" },
    { posicao: "16", titulo: "Houstonfornication", duracao: "3:37" },
    { posicao: "17", titulo: "Coffee Bean", duracao: "3:29" },
  ],
  861083: [
    { posicao: "A1", titulo: "Let It Happen", duracao: "" },
    { posicao: "A2", titulo: "Nangs", duracao: "" },
    { posicao: "A3", titulo: "The Moment", duracao: "" },
    { posicao: "B1", titulo: "Yes I'm Changing", duracao: "" },
    { posicao: "B2", titulo: "Eventually", duracao: "" },
    { posicao: "B3", titulo: "Gossip", duracao: "" },
    { posicao: "C1", titulo: "The Less I Know The Better", duracao: "" },
    { posicao: "C2", titulo: "Past Life", duracao: "" },
    { posicao: "C3", titulo: "Disciples", duracao: "" },
    { posicao: "C4", titulo: "Cause I'm A Man", duracao: "" },
    { posicao: "D1", titulo: "Reality In Motion", duracao: "" },
    { posicao: "D2", titulo: "Love / Paranoia", duracao: "" },
    { posicao: "D3", titulo: "New Person, Same Old Mistakes", duracao: "" },
  ],
  8883: [
    { posicao: "A1", titulo: "Wanna Be Startin' Somethin'", duracao: "6:02" },
    { posicao: "A2", titulo: "Baby Be Mine", duracao: "4:20" },
    { posicao: "A3", titulo: "The Girl Is Mine", duracao: "3:42" },
    { posicao: "A4", titulo: "Thriller", duracao: "5:57" },
    { posicao: "B1", titulo: "Beat It", duracao: "4:17" },
    { posicao: "B2", titulo: "Billie Jean", duracao: "4:57" },
    { posicao: "B3", titulo: "Human Nature", duracao: "4:05" },
    { posicao: "B4", titulo: "P.Y.T. (Pretty Young Thing)", duracao: "3:58" },
    { posicao: "B5", titulo: "The Lady In My Life", duracao: "4:57" },
  ],
  57279: [
    { posicao: "1", titulo: "Intro", duracao: "0:47" },
    { posicao: "2", titulo: "Lost Ones", duracao: "5:33" },
    { posicao: "3", titulo: "Ex-Factor", duracao: "5:26" },
    { posicao: "4", titulo: "To Zion", duracao: "6:09" },
    { posicao: "5", titulo: "Doo Wop (That Thing)", duracao: "5:20" },
    { posicao: "6", titulo: "Superstar", duracao: "4:57" },
    { posicao: "7", titulo: "Final Hour", duracao: "4:16" },
    { posicao: "8", titulo: "When It Hurts So Bad", duracao: "5:42" },
    { posicao: "9", titulo: "I Used To Love Him", duracao: "5:39" },
    { posicao: "10", titulo: "Forgive Them Father", duracao: "5:15" },
    { posicao: "11", titulo: "Every Ghetto, Every City", duracao: "5:14" },
    { posicao: "12", titulo: "Nothing Even Matters", duracao: "5:50" },
    { posicao: "13", titulo: "Everything Is Everything", duracao: "4:53" },
    { posicao: "14", titulo: "The Miseducation Of Lauryn Hill", duracao: "4:17" },
    { posicao: "15", titulo: "Can't Take My Eyes Off Of You", duracao: "3:41" },
    { posicao: "16", titulo: "Tell Him", duracao: "4:40" },
  ],
  810214: [
    { posicao: "1", titulo: "Wesley's Theory", duracao: "4:47" },
    { posicao: "2", titulo: "For Free? (Interlude)", duracao: "2:10" },
    { posicao: "3", titulo: "King Kunta", duracao: "3:54" },
    { posicao: "4", titulo: "Institutionalized", duracao: "4:31" },
    { posicao: "5", titulo: "These Walls", duracao: "5:00" },
    { posicao: "6", titulo: "U", duracao: "4:28" },
    { posicao: "7", titulo: "Alright", duracao: "3:39" },
    { posicao: "8", titulo: "For Sale? (Interlude)", duracao: "4:51" },
    { posicao: "9", titulo: "Momma", duracao: "4:43" },
    { posicao: "10", titulo: "Hood Politics", duracao: "4:52" },
    { posicao: "11", titulo: "How Much A Dollar Cost", duracao: "4:21" },
    { posicao: "12", titulo: "Complexion (A Zulu Love)", duracao: "4:23" },
    { posicao: "13", titulo: "The Blacker The Berry", duracao: "5:28" },
    { posicao: "14", titulo: "You Ain't Gotta Lie (Momma Said)", duracao: "4:01" },
    { posicao: "15", titulo: "I", duracao: "5:36" },
    { posicao: "16", titulo: "Mortal Man", duracao: "12:07" },
  ],
  10362: [
    { posicao: "A1", titulo: "Speak To Me", duracao: "" },
    { posicao: "A2", titulo: "Breathe In The Air", duracao: "" },
    { posicao: "A3", titulo: "On The Run", duracao: "" },
    { posicao: "A4", titulo: "Time", duracao: "" },
    { posicao: "A5", titulo: "The Great Gig In The Sky", duracao: "" },
    { posicao: "B1", titulo: "Money", duracao: "" },
    { posicao: "B2", titulo: "Us And Them", duracao: "" },
    { posicao: "B3", titulo: "Any Colour You Like", duracao: "" },
    { posicao: "B4", titulo: "Brain Damage", duracao: "" },
    { posicao: "B5", titulo: "Eclipse", duracao: "" },
  ],
  6440: [
    { posicao: "A1", titulo: "Fight Fire With Fire", duracao: "4:44" },
    { posicao: "A2", titulo: "Ride The Lightning", duracao: "6:36" },
    { posicao: "A3", titulo: "For Whom The Bell Tolls", duracao: "5:10" },
    { posicao: "A4", titulo: "Fade To Black", duracao: "6:56" },
    { posicao: "B1", titulo: "Trapped Under Ice", duracao: "4:03" },
    { posicao: "B2", titulo: "Escape", duracao: "4:23" },
    { posicao: "B3", titulo: "Creeping Death", duracao: "6:36" },
    { posicao: "B4", titulo: "The Call Of Ktulu", duracao: "8:52" },
  ],
  593987: [
    { posicao: "A1", titulo: "Do I Wanna Know?", duracao: "4:32" },
    { posicao: "A2", titulo: "R U Mine?", duracao: "3:21" },
    { posicao: "A3", titulo: "One For The Road", duracao: "3:26" },
    { posicao: "A4", titulo: "Arabella", duracao: "3:27" },
    { posicao: "A5", titulo: "I Want It All", duracao: "3:05" },
    { posicao: "A6", titulo: "No.1 Party Anthem", duracao: "4:03" },
    { posicao: "B1", titulo: "Mad Sounds", duracao: "3:25" },
    { posicao: "B2", titulo: "Fireside", duracao: "3:01" },
    { posicao: "B3", titulo: "Why'd You Only Call Me When You're High?", duracao: "2:41" },
    { posicao: "B4", titulo: "Snap Out Of It ", duracao: "3:13" },
    { posicao: "B5", titulo: "Knee Socks", duracao: "4:17" },
    { posicao: "B6", titulo: "I Wanna Be Yours", duracao: "3:04" },
  ],
  35665: [
    { posicao: "1", titulo: "Soldier Side - Intro", duracao: "1:03" },
    { posicao: "2", titulo: "B.Y.O.B.", duracao: "4:15" },
    { posicao: "3", titulo: "Revenga", duracao: "3:48" },
    { posicao: "4", titulo: "Cigaro", duracao: "2:11" },
    { posicao: "5", titulo: "Radio/Video", duracao: "4:09" },
    { posicao: "6", titulo: "This Cocaine Makes Me Feel Like I'm On This Song", duracao: "2:08" },
    { posicao: "7", titulo: "Violent Pornography", duracao: "3:31" },
    { posicao: "8", titulo: "Question!", duracao: "3:20" },
    { posicao: "9", titulo: "Sad Statue", duracao: "3:25" },
    { posicao: "10", titulo: "Old School Hollywood", duracao: "2:56" },
    { posicao: "11", titulo: "Lost In Hollywood", duracao: "5:20" },
  ],
  1112335: [
    { posicao: "1", titulo: "Me And Your Mama", duracao: "6:19" },
    { posicao: "2", titulo: "Have Some Love", duracao: "3:44" },
    { posicao: "3", titulo: "Boogieman", duracao: "3:37" },
    { posicao: "4", titulo: "Zombies", duracao: "4:42" },
    { posicao: "5", titulo: "Riot", duracao: "2:05" },
    { posicao: "6", titulo: "Redbone", duracao: "5:27" },
    { posicao: "7", titulo: "California", duracao: "2:45" },
    { posicao: "8", titulo: "Terrified", duracao: "4:16" },
    { posicao: "9", titulo: "Baby Boy", duracao: "6:22" },
    { posicao: "10", titulo: "The Night Me And Your Mama Met", duracao: "3:34" },
    { posicao: "11", titulo: "Stand Tall", duracao: "6:11" },
  ],
  950545: [
    { posicao: "1", titulo: "Consideration", duracao: "2:41" },
    { posicao: "2", titulo: "James Joint", duracao: "1:12" },
    { posicao: "3", titulo: "Kiss It Better", duracao: "4:13" },
    { posicao: "4", titulo: "Work", duracao: "3:39" },
    { posicao: "5", titulo: "Desperado", duracao: "3:07" },
    { posicao: "6", titulo: "Woo", duracao: "3:56" },
    { posicao: "7", titulo: "Needed Me", duracao: "3:12" },
    { posicao: "8", titulo: "Yeah, I Said It", duracao: "2:13" },
    { posicao: "9", titulo: "Same Ol' Mistakes", duracao: "6:37" },
    { posicao: "10", titulo: "Never Ending", duracao: "3:23" },
    { posicao: "11", titulo: "Love On The Brain", duracao: "3:44" },
    { posicao: "12", titulo: "Higher", duracao: "2:01" },
    { posicao: "13", titulo: "Close To You", duracao: "3:43" },
  ],
  1164779: [
    { posicao: "1", titulo: "Blood", duracao: "1:58" },
    { posicao: "2", titulo: "DNA", duracao: "3:05" },
    { posicao: "3", titulo: "Yah", duracao: "2:39" },
    { posicao: "4", titulo: "Element", duracao: "3:28" },
    { posicao: "5", titulo: "Feel", duracao: "3:34" },
    { posicao: "6", titulo: "Loyalty", duracao: "3:47" },
    { posicao: "7", titulo: "Pride", duracao: "4:31" },
    { posicao: "8", titulo: "Humble", duracao: "2:56" },
    { posicao: "9", titulo: "Lust", duracao: "5:08" },
    { posicao: "10", titulo: "Love", duracao: "3:31" },
    { posicao: "11", titulo: "XXX", duracao: "4:14" },
    { posicao: "12", titulo: "Fear", duracao: "6:54" },
    { posicao: "13", titulo: "God", duracao: "4:08" },
    { posicao: "14", titulo: "Duckworth", duracao: "4:08" },
  ],
  13814: [
    { posicao: "A1", titulo: "Smells Like Teen Spirit", duracao: "5:00" },
    { posicao: "A2", titulo: "In Bloom", duracao: "4:13" },
    { posicao: "A3", titulo: "Come As You Are", duracao: "3:38" },
    { posicao: "A4", titulo: "Breed", duracao: "3:03" },
    { posicao: "A5", titulo: "Lithium", duracao: "4:16" },
    { posicao: "A6", titulo: "Polly", duracao: "2:56" },
    { posicao: "B1", titulo: "Territorial Pissings", duracao: "2:22" },
    { posicao: "B2", titulo: "Drain You", duracao: "3:43" },
    { posicao: "B3", titulo: "Lounge Act", duracao: "2:35" },
    { posicao: "B4", titulo: "Stay Away", duracao: "3:30" },
    { posicao: "B5", titulo: "On A Plain", duracao: "3:12" },
    { posicao: "B6", titulo: "Something In The Way", duracao: "3:43" },
  ],
  1473270: [
    { posicao: "1", titulo: "10AM / Save The World", duracao: "3:46" },
    { posicao: "2", titulo: "Overdue", duracao: "2:46" },
    { posicao: "3", titulo: "Don't Come Out The House", duracao: "2:48" },
    { posicao: "4", titulo: "Dreamcatcher", duracao: "3:31" },
    { posicao: "5", titulo: "Space Cadet", duracao: "3:23" },
    { posicao: "6", titulo: "10 Freaky Girls", duracao: "3:28" },
    { posicao: "7", titulo: "Up To Something", duracao: "3:04" },
    { posicao: "8", titulo: "Only 1 (Interlude)", duracao: "1:20" },
    { posicao: "9", titulo: "Lesbian", duracao: "3:26" },
    { posicao: "10", titulo: "Borrowed Love", duracao: "3:50" },
    { posicao: "11", titulo: "Only You", duracao: "3:38" },
    { posicao: "12", titulo: "No More", duracao: "4:25" },
    { posicao: "13", titulo: "No Complaints", duracao: "4:25" },
  ],
  1085420: [
    { posicao: "1", titulo: "The Ends", duracao: "3:21" },
    { posicao: "2", titulo: "Way Back", duracao: "4:32" },
    { posicao: "3", titulo: "Coordinate", duracao: "3:46" },
    { posicao: "4", titulo: "Through The Late Night", duracao: "4:46" },
    { posicao: "5", titulo: "Beibs In The Trap", duracao: "3:33" },
    { posicao: "6", titulo: "SDP Interlude", duracao: "3:11" },
    { posicao: "7", titulo: "Sweet Sweet", duracao: "3:42" },
    { posicao: "8", titulo: "Outside", duracao: "2:56" },
    { posicao: "9", titulo: "Goosebumps", duracao: "4:03" },
    { posicao: "10", titulo: "First Take", duracao: "5:13" },
    { posicao: "11", titulo: "Pick Up The Phone", duracao: "4:12" },
    { posicao: "12", titulo: "Lose", duracao: "3:20" },
    { posicao: "13", titulo: "Guidance", duracao: "3:27" },
    { posicao: "14", titulo: "Wonderful", duracao: "3:36" },
  ],
  4119973: [
    { posicao: "1", titulo: "E85", duracao: "2:33" },
    { posicao: "2", titulo: "Body", duracao: "2:35" },
    { posicao: "3", titulo: "Rendezvous ", duracao: "2:26" },
    { posicao: "4", titulo: "Secondhand", duracao: "3:46" },
    { posicao: "5", titulo: "Tiramisu", duracao: "2:18" },
    { posicao: "6", titulo: "ATM", duracao: "3:00" },
    { posicao: "7", titulo: "Long Way To Calabasas ", duracao: "1:39" },
    { posicao: "8", titulo: "Rosary", duracao: "3:14" },
    { posicao: "9", titulo: "All The Signs", duracao: "3:20" },
    { posicao: "10", titulo: "Call Back", duracao: "2:03" },
    { posicao: "11", titulo: "Tuition", duracao: "2:49" },
    { posicao: "12", titulo: "K9", duracao: "2:34" },
    { posicao: "13", titulo: "Excavator", duracao: "3:31" },
    { posicao: "14", titulo: "Gemstone", duracao: "2:01" },
    { posicao: "15", titulo: "Opposite", duracao: "2:37" },
    { posicao: "16", titulo: "TMU", duracao: "3:00" },
    { posicao: "17", titulo: "Pleasure’s Mine", duracao: "2:57" },
    { posicao: "18", titulo: "Sweet Home", duracao: "3:20" },
  ],
  8497: [
    { posicao: "1", titulo: "Good Morning", duracao: "3:15" },
    { posicao: "2", titulo: "Champion", duracao: "2:47" },
    { posicao: "3", titulo: "Stronger", duracao: "5:12" },
    { posicao: "4", titulo: "I Wonder", duracao: "4:03" },
    { posicao: "5", titulo: "Good Life", duracao: "3:27" },
    { posicao: "6", titulo: "Can't Tell Me Nothing", duracao: "4:31" },
    { posicao: "7", titulo: "Barry Bonds", duracao: "3:24" },
    { posicao: "8", titulo: "Drunk And Hot Girls", duracao: "5:13" },
    { posicao: "9", titulo: "Flashing Lights", duracao: "3:57" },
    { posicao: "10", titulo: "Everything I Am", duracao: "3:47" },
    { posicao: "11", titulo: "The Glory", duracao: "3:32" },
    { posicao: "12", titulo: "Homecoming", duracao: "3:23" },
    { posicao: "13", titulo: "Big Brother", duracao: "4:47" },
  ],
  2670629: [
    { posicao: "1-1", titulo: "Moscow Mule", duracao: "4:05" },
    { posicao: "1-2", titulo: "Después de la Playa", duracao: "3:50" },
    { posicao: "1-3", titulo: "Me Porto Bonito", duracao: "2:58" },
    { posicao: "1-4", titulo: "Tití Me Preguntó", duracao: "4:03" },
    { posicao: "1-5", titulo: "Un Ratito", duracao: "2:56" },
    { posicao: "1-6", titulo: "Yo No Soy Celoso", duracao: "3:50" },
    { posicao: "1-7", titulo: "Tarot", duracao: "3:57" },
    { posicao: "1-8", titulo: "Neverita", duracao: "2:53" },
    { posicao: "1-9", titulo: "La Corriente", duracao: "3:18" },
    { posicao: "1-10", titulo: "Efecto", duracao: "3:33" },
    { posicao: "1-11", titulo: "Party", duracao: "3:47" },
    { posicao: "2-1", titulo: "Aguacero", duracao: "3:30" },
    { posicao: "2-2", titulo: "Enseñame a Bailar", duracao: "2:56" },
    { posicao: "2-3", titulo: "Ojitos Lindos", duracao: "4:18" },
    { posicao: "2-4", titulo: "Dos Mil 16", duracao: "3:28" },
    { posicao: "2-5", titulo: "El Apagón", duracao: "3:21" },
    { posicao: "2-6", titulo: "Otro Atardecer", duracao: "4:04" },
    { posicao: "2-7", titulo: "Un Coco", duracao: "3:16" },
    { posicao: "2-8", titulo: "Andrea", duracao: "5:39" },
    { posicao: "2-9", titulo: "Me Fuí de Vacaciones", duracao: "3:00" },
    { posicao: "2-10", titulo: "Un Verano Sin Ti", duracao: "2:28" },
    { posicao: "2-11", titulo: "Agosto", duracao: "2:19" },
    { posicao: "2-12", titulo: "Callaita", duracao: "4:10" },
  ],
  883244: [
    { posicao: "1", titulo: "Pornography", duracao: "3:51" },
    { posicao: "2", titulo: "Oh My Dis Side", duracao: "5:51" },
    { posicao: "3", titulo: "3500", duracao: "7:41" },
    { posicao: "4", titulo: "Wasted", duracao: "3:55" },
    { posicao: "5", titulo: "90210", duracao: "5:39" },
    { posicao: "6", titulo: "Pray 4 Love", duracao: "5:07" },
    { posicao: "7", titulo: "Nightcrawler", duracao: "5:21" },
    { posicao: "8", titulo: "Piss On Your Grave", duracao: "2:46" },
    { posicao: "9", titulo: "Antidote", duracao: "4:22" },
    { posicao: "10", titulo: "Impossible", duracao: "4:02" },
    { posicao: "11", titulo: "Maria I'm Drunk", duracao: "5:49" },
    { posicao: "12", titulo: "Flying High", duracao: "3:28" },
    { posicao: "13", titulo: "I Can Tell", duracao: "3:55" },
    { posicao: "14", titulo: "Apple Pie", duracao: "3:39" },
  ],
  4155436: [
    { posicao: "A1", titulo: "Leviticus", duracao: "" },
    { posicao: "A2", titulo: "2009 Reggie Bush", duracao: "" },
    { posicao: "A3", titulo: "Bloodsweat", duracao: "" },
    { posicao: "A4", titulo: "Angel Grove", duracao: "" },
    { posicao: "A5", titulo: "Whatever Floats Your Boat Will Definitely Sink My Ship", duracao: "" },
    { posicao: "B1", titulo: "MSY", duracao: "" },
    { posicao: "B2", titulo: "Old Addicts, New Habits", duracao: "" },
    { posicao: "B3", titulo: "Frenzy", duracao: "" },
    { posicao: "B4", titulo: "Hypernormalisation", duracao: "" },
    { posicao: "B5", titulo: "Fuck Ups", duracao: "" },
  ],
  3716847: [
    { posicao: "1", titulo: "Nuevayol", duracao: "3:03" },
    { posicao: "2", titulo: "Voy A Llevarte Pa PR", duracao: "2:36" },
    { posicao: "3", titulo: "Baile Inolvidable", duracao: "6:07" },
    { posicao: "4", titulo: "Perfumito Nuevo", duracao: "3:20" },
    { posicao: "5", titulo: "Weltita", duracao: "3:07" },
    { posicao: "6", titulo: "Veldá", duracao: "3:55" },
    { posicao: "7", titulo: "El Clúb", duracao: "3:42" },
    { posicao: "8", titulo: "Ketu Tecré", duracao: "4:10" },
    { posicao: "9", titulo: "Bokete", duracao: "3:35" },
    { posicao: "10", titulo: "Kloufrens", duracao: "3:19" },
    { posicao: "11", titulo: "Turista", duracao: "3:10" },
    { posicao: "12", titulo: "Café Con Ron", duracao: "3:48" },
    { posicao: "13", titulo: "Pitorro De Coco", duracao: "3:26" },
    { posicao: "14", titulo: "Lo Que Le Pasó A Hawaii", duracao: "3:49" },
    { posicao: "15", titulo: "EOO", duracao: "3:24" },
    { posicao: "16", titulo: "DTMF", duracao: "3:57" },
    { posicao: "17", titulo: "La Mudanza", duracao: "3:33" },
  ],
  288153: [
    { posicao: "1", titulo: "Dark Fantasy", duracao: "4:40" },
    { posicao: "2", titulo: "Gorgeous", duracao: "5:57" },
    { posicao: "3", titulo: "Power", duracao: "4:52" },
    { posicao: "4", titulo: "All Of The Lights (Interlude)", duracao: "1:02" },
    { posicao: "5", titulo: "All Of The Lights", duracao: "4:59" },
    { posicao: "6", titulo: "Monster", duracao: "6:18" },
    { posicao: "7", titulo: "So Appalled", duracao: "6:37" },
    { posicao: "8", titulo: "Devil In A New Dress", duracao: "5:51" },
    { posicao: "9", titulo: "Runaway", duracao: "9:07" },
    { posicao: "10", titulo: "Hell Of A Life", duracao: "5:27" },
    { posicao: "11", titulo: "Blame Game", duracao: "7:49" },
    { posicao: "12", titulo: "Lost In The World", duracao: "4:16" },
    { posicao: "13", titulo: "Who Will Survive In America", duracao: "1:38" },
    { posicao: "14", titulo: "See Me Now (Bonus Track)", duracao: "6:03" },
  ],
  454284: [
    { posicao: "1", titulo: "Start", duracao: "0:45" },
    { posicao: "2", titulo: "Thinkin Bout You", duracao: "3:20" },
    { posicao: "3", titulo: "Fertilizer", duracao: "0:39" },
    { posicao: "4", titulo: "Sierra Leone", duracao: "2:28" },
    { posicao: "5", titulo: "Sweet Life", duracao: "4:22" },
    { posicao: "6", titulo: "Not Just Money", duracao: "0:59" },
    { posicao: "7", titulo: "Super Rich Kids", duracao: "5:04" },
    { posicao: "8", titulo: "Pilot Jones", duracao: "3:04" },
    { posicao: "9", titulo: "Crack Rock", duracao: "3:44" },
    { posicao: "10", titulo: "Pyramids", duracao: "9:52" },
    { posicao: "11", titulo: "Lost", duracao: "3:54" },
    { posicao: "12", titulo: "White", duracao: "1:16" },
    { posicao: "13", titulo: "Monks", duracao: "3:20" },
    { posicao: "14", titulo: "Bad Religion", duracao: "2:55" },
    { posicao: "15", titulo: "Pink Matter", duracao: "4:28" },
    { posicao: "16", titulo: "Forrest Gump", duracao: "3:14" },
    { posicao: "17.1", titulo: "End", duracao: "2:14" },
    { posicao: "17.2", titulo: "(silence)", duracao: "1:30" },
    { posicao: "17.3", titulo: "Golden Girl", duracao: "4:59" },
  ],
  3975953: [
    { posicao: "A1", titulo: "Sherane A.K.A Master Splinter's Daughter", duracao: "" },
    { posicao: "A2", titulo: "Bitch, Don't Kill My Vibe", duracao: "" },
    { posicao: "A3", titulo: "Backseat Freestyle", duracao: "" },
    { posicao: "A4", titulo: "The Art Of Peer Pressure", duracao: "" },
    { posicao: "B1", titulo: "Money Trees", duracao: "" },
    { posicao: "B2", titulo: "Poetic Justice", duracao: "" },
    { posicao: "B3", titulo: "Good Kid", duracao: "" },
    { posicao: "B4", titulo: "M.A.A.D City", duracao: "" },
    { posicao: "C1", titulo: "Swimming Pools (Drank) (Extended Version)", duracao: "" },
    { posicao: "C2", titulo: "Sing About Me, I'm Dying Of Thirst", duracao: "" },
    { posicao: "C3", titulo: "Real", duracao: "" },
    { posicao: "D1", titulo: "Compton", duracao: "" },
    { posicao: "D2", titulo: "The Recipe", duracao: "" },
    { posicao: "D3", titulo: "Black Boy Fly", duracao: "" },
    { posicao: "D4", titulo: "Now Or Never", duracao: "" },
  ],
  3227581: [
    { posicao: "1", titulo: "Down By Law", duracao: "3:31" },
    { posicao: "2", titulo: "Shed Tears", duracao: "4:49" },
    { posicao: "3", titulo: "Run", duracao: "4:45" },
    { posicao: "4", titulo: "Nrich", duracao: "4:40" },
    { posicao: "5", titulo: "Talk'n That Shit!", duracao: "2:54" },
    { posicao: "6", titulo: "Slummer", duracao: "4:35" },
    { posicao: "7", titulo: "Scientists & Engineers", duracao: "4:13" },
    { posicao: "8", titulo: "Two Days", duracao: "2:14" },
    { posicao: "9", titulo: "Spaceship Views", duracao: "3:12" },
    { posicao: "10", titulo: "Exit 9", duracao: "2:42" },
    { posicao: "11", titulo: "Something For Junkies", duracao: "4:38" },
    { posicao: "12", titulo: "Motherless", duracao: "3:53" },
    { posicao: "13", titulo: "Don't Let The Devil", duracao: "2:45" },
    { posicao: "14", titulo: "High & Holy", duracao: "4:53" },
  ],
  2890219: [
    { posicao: "1", titulo: "On Time", duracao: "2:48" },
    { posicao: "2", titulo: "Superhero (Heroes & Villains)", duracao: "3:02" },
    { posicao: "3", titulo: "Too Many Nights", duracao: "3:19" },
    { posicao: "4", titulo: "Raindrops (Insane) ", duracao: "3:08" },
    { posicao: "5", titulo: "Umbrella", duracao: "3:42" },
    { posicao: "6", titulo: "Trance", duracao: "3:14" },
    { posicao: "7", titulo: "Around Me ", duracao: "3:11" },
    { posicao: "8", titulo: "Metro Spider", duracao: "2:54" },
    { posicao: "9", titulo: "I Can't Save You (Interlude)", duracao: "1:30" },
    { posicao: "10", titulo: "Creepin'", duracao: "3:41" },
    { posicao: "11", titulo: "Niagara Falls (Foot Or 2)", duracao: "3:27" },
    { posicao: "12", titulo: "Walk Em Down (Don't Kill Civilians)", duracao: "5:10" },
    { posicao: "13", titulo: "Lock On Me", duracao: "2:54" },
    { posicao: "14", titulo: "Feel The Fiyaaaah", duracao: "3:09" },
    { posicao: "15", titulo: "All The Money", duracao: "2:47" },
  ],
  573645: [
    { posicao: "A1", titulo: "Chega Mais", duracao: "3:50" },
    { posicao: "A2", titulo: "Papai Me Empresta O Carro", duracao: "3:08" },
    { posicao: "A3", titulo: "Doce Vampiro", duracao: "4:24" },
    { posicao: "A4", titulo: "Corre-Corre", duracao: "4:40" },
    { posicao: "B1", titulo: "Mania De Você\t", duracao: "4:51" },
    { posicao: "B2", titulo: "Elvira Pagã", duracao: "3:17" },
    { posicao: "B3", titulo: "Maria Mole", duracao: "5:17" },
    { posicao: "B4", titulo: "Arrombou A Festa II", duracao: "3:33" },
  ],
  841256: [
    { posicao: "1", titulo: "Holy Ghost", duracao: "3:11" },
    { posicao: "2", titulo: "Canal St.", duracao: "3:47" },
    { posicao: "3", titulo: "Fine Whine", duracao: "3:38" },
    { posicao: "4", titulo: "L$D", duracao: "3:58" },
    { posicao: "5", titulo: "Excuse Me", duracao: "3:58" },
    { posicao: "6", titulo: "JD", duracao: "1:45" },
    { posicao: "7", titulo: "Lord Pretty Flacko Jodye 2", duracao: "2:06" },
    { posicao: "8", titulo: "Electric Body", duracao: "4:15" },
    { posicao: "9", titulo: "Jukebox Joints", duracao: "5:23" },
    { posicao: "10", titulo: "Max B", duracao: "4:01" },
    { posicao: "11", titulo: "Pharsyde", duracao: "3:42" },
    { posicao: "12", titulo: "Wavybone", duracao: "5:03" },
    { posicao: "13", titulo: "West Side Highway", duracao: "2:56" },
    { posicao: "14", titulo: "Better Things", duracao: "3:19" },
    { posicao: "15", titulo: "M'$", duracao: "3:53" },
    { posicao: "16", titulo: "Dreams (Interlude)", duracao: "2:16" },
    { posicao: "17", titulo: "Everyday", duracao: "4:20" },
    { posicao: "18", titulo: "Back Home", duracao: "4:38" },
  ],
  430850: [
    { posicao: "1-1", titulo: "Sou + Você", duracao: "1:48" },
    { posicao: "1-2", titulo: "Vivão E Vivendo", duracao: "1:58" },
    { posicao: "1-3", titulo: "V.L. (Intro)", duracao: "0:24" },
    { posicao: "1-4", titulo: "V.L. (Parte I)", duracao: "5:03" },
    { posicao: "1-5", titulo: "Negro Drama", duracao: "6:52" },
    { posicao: "1-6", titulo: "A Vítima", duracao: "7:20" },
    { posicao: "1-7", titulo: "Na Fé Firmão", duracao: "6:05" },
    { posicao: "1-8", titulo: "12 De Outubro", duracao: "3:31" },
    { posicao: "1-9", titulo: "Eu Sou 157", duracao: "8:50" },
    { posicao: "1-10", titulo: "A Vida É Desafio", duracao: "7:13" },
    { posicao: "1-11", titulo: "1 Por Amor 2 Por Dinheiro", duracao: "6:58" },
    { posicao: "2-1", titulo: "De Volta A Cena", duracao: "2:01" },
    { posicao: "2-2", titulo: "Otus 500", duracao: "2:12" },
    { posicao: "2-3", titulo: "Crime Vai E Vem", duracao: "7:55" },
    { posicao: "2-4", titulo: "Jesus Chorou", duracao: "7:52" },
    { posicao: "2-5", titulo: "Fone (Intro)", duracao: "1:56" },
    { posicao: "2-6", titulo: "Estilo Cachorro", duracao: "6:18" },
    { posicao: "2-7", titulo: "V.L. (Parte II)", duracao: "5:50" },
    { posicao: "2-8", titulo: "Expresso Da Meia-Noite", duracao: "5:22" },
    { posicao: "2-9", titulo: "Trutas E Quebradas", duracao: "6:17" },
    { posicao: "2-10", titulo: "Da Ponte Pra Cá", duracao: "8:48" },
  ],
  511822: [
    { posicao: "1", titulo: "Long Live A$AP", duracao: "" },
    { posicao: "2", titulo: "Goldie", duracao: "" },
    { posicao: "3", titulo: "PMW (All I Really Need)", duracao: "" },
    { posicao: "4", titulo: "LVL", duracao: "" },
    { posicao: "5", titulo: "Hell", duracao: "" },
    { posicao: "6", titulo: "Pain", duracao: "" },
    { posicao: "7", titulo: "F**kin' Problems", duracao: "" },
    { posicao: "8", titulo: "Wild For The Night", duracao: "" },
    { posicao: "9", titulo: "1 Train", duracao: "" },
    { posicao: "10", titulo: "Fashion Killa", duracao: "" },
    { posicao: "11", titulo: "Phoenix", duracao: "" },
    { posicao: "12", titulo: "Suddenly", duracao: "" },
    { posicao: "13", titulo: "Jodye", duracao: "" },
    { posicao: "14", titulo: "Ghetto Symphony", duracao: "" },
    { posicao: "15", titulo: "Angels", duracao: "" },
    { posicao: "16", titulo: "I Come Apart", duracao: "" },
  ],
  2412268: [
    { posicao: "1", titulo: "Trademark USA", duracao: "4:30" },
    { posicao: "2", titulo: "Pink Panties", duracao: "2:43" },
    { posicao: "3", titulo: "Scapegoats", duracao: "1:16" },
    { posicao: "4", titulo: "Range Brothers", duracao: "5:16" },
    { posicao: "5", titulo: "Issues", duracao: "3:39" },
    { posicao: "6", titulo: "Gorgeous", duracao: "2:20" },
    { posicao: "7", titulo: "South Africa", duracao: "2:54" },
    { posicao: "8", titulo: "Lost Souls", duracao: "4:29" },
    { posicao: "9", titulo: "Cocoa", duracao: "3:49" },
    { posicao: "10", titulo: "Family Ties", duracao: "4:12" },
    { posicao: "11", titulo: "Scars", duracao: "4:26" },
    { posicao: "12", titulo: "Durag Activity", duracao: "3:44" },
    { posicao: "13", titulo: "Booman", duracao: "2:35" },
    { posicao: "14", titulo: "First Order Of Business", duracao: "2:48" },
    { posicao: "15", titulo: "Vent", duracao: "2:16" },
    { posicao: "16", titulo: "16", duracao: "2:36" },
  ],
  3524320: [
    { posicao: "1", titulo: "Kryptonite", duracao: "3:02" },
    { posicao: "2", titulo: "Tore Up", duracao: "2:06" },
    { posicao: "3", titulo: "Brother Stone", duracao: "3:22" },
    { posicao: "4", titulo: "Attitude", duracao: "2:41" },
    { posicao: "1", titulo: "Bandit", duracao: "2:27" },
    { posicao: "2", titulo: "Glock", duracao: "3:48" },
    { posicao: "3", titulo: "Ice Age", duracao: "3:38" },
    { posicao: "4", titulo: "4X4", duracao: "3:22" },
    { posicao: "1", titulo: "Purple Rain", duracao: "3:27" },
    { posicao: "2", titulo: "New Drop", duracao: "3:37" },
    { posicao: "3", titulo: "Backstreets", duracao: "3:17" },
    { posicao: "4", titulo: "Deep In The Water", duracao: "2:50" },
    { posicao: "1", titulo: "Inside", duracao: "4:10" },
    { posicao: "2", titulo: "5 To 10", duracao: "3:13" },
    { posicao: "3", titulo: "Last Laugh", duracao: "4:01" },
    { posicao: "4", titulo: "Hardstone National Anthem", duracao: "2:41" },
    { posicao: "5", titulo: "Attitude (Video)", duracao: "3:13" },
    { posicao: "6", titulo: "Bandit (Video)", duracao: "3:48" },
    { posicao: "7", titulo: "Deep In The Water (Video)", duracao: "2:57" },
  ],
  3002207: [
    { posicao: "1", titulo: "LoveSickness", duracao: "1:54" },
    { posicao: "2", titulo: "Let Her Go", duracao: "3:12" },
    { posicao: "3", titulo: "Leave The Club", duracao: "3:42" },
    { posicao: "4", titulo: "4 Me", duracao: "2:40" },
    { posicao: "5", titulo: "Go Down", duracao: "3:30" },
    { posicao: "6", titulo: "Time Heals All", duracao: "3:53" },
    { posicao: "7", titulo: "Leather Coat", duracao: "4:01" },
    { posicao: "8", titulo: "Honeymoon", duracao: "3:04" },
    { posicao: "9", titulo: "Private Landing", duracao: "3:58" },
    { posicao: "10", titulo: "Slow Motion", duracao: "2:48" },
    { posicao: "11", titulo: "Do It Right", duracao: "2:54" },
    { posicao: "12", titulo: "If I Had", duracao: "3:28" },
    { posicao: "13", titulo: "Company Pt. 3", duracao: "3:00" },
    { posicao: "14", titulo: "Bus Stop", duracao: "3:56" },
    { posicao: "15", titulo: "Cinderella", duracao: "3:46" },
    { posicao: "16", titulo: "Encouragement", duracao: "2:56" },
  ],
  107391: [
    { posicao: "A1", titulo: "Blue Hawaii", duracao: "2:35" },
    { posicao: "A2", titulo: "Almost Always True", duracao: "2:24" },
    { posicao: "A3", titulo: "Aloha Oe", duracao: "1:54" },
    { posicao: "A4", titulo: "No More", duracao: "2:22" },
    { posicao: "A5", titulo: "Can't Help Falling In Love", duracao: "2:59" },
    { posicao: "A6", titulo: "Rock-A-Hula Baby", duracao: "1:58" },
    { posicao: "A7", titulo: "Moonlight Swim", duracao: "2:18" },
    { posicao: "B1", titulo: "Ku-u-i-po (Hawaiian Sweetheart)", duracao: "2:22" },
    { posicao: "B2", titulo: "Ito Eats", duracao: "1:25" },
    { posicao: "B3", titulo: "Slicin' Sand", duracao: "1:34" },
    { posicao: "B4", titulo: "Hawaiian Sunset", duracao: "2:30" },
    { posicao: "B5", titulo: "Beach Boys Blue", duracao: "2:00" },
    { posicao: "B6", titulo: "Island Of Love (Kauai)", duracao: "2:40" },
    { posicao: "B7", titulo: "Hawaiian Wedding Song", duracao: "2:48" },
  ],
  923402: [
    { posicao: "1", titulo: "Digital Dash", duracao: "3:51" },
    { posicao: "2", titulo: "Big Rings", duracao: "3:37" },
    { posicao: "3", titulo: "Live From The Gutter", duracao: "3:31" },
    { posicao: "4", titulo: "Diamonds Dancing", duracao: "5:14" },
    { posicao: "5", titulo: "Scholarships", duracao: "3:29" },
    { posicao: "6", titulo: "Plastic Bag", duracao: "3:22" },
    { posicao: "7", titulo: "I'm The Plug", duracao: "3:00" },
    { posicao: "8", titulo: "Change Locations", duracao: "3:40" },
    { posicao: "9", titulo: "Jumpman", duracao: "3:25" },
    { posicao: "10", titulo: "Jersey", duracao: "3:08" },
    { posicao: "11", titulo: "30 For 30 Freestyle", duracao: "4:13" },
  ],
  1046042: [
    { posicao: "1", titulo: "Nikes", duracao: "5:14" },
    { posicao: "2", titulo: "Ivy", duracao: "4:09" },
    { posicao: "3", titulo: "Pink + White", duracao: "3:04" },
    { posicao: "4", titulo: "Be Yourself", duracao: "1:26" },
    { posicao: "5", titulo: "Solo", duracao: "4:17" },
    { posicao: "6", titulo: "Skyline To", duracao: "3:04" },
    { posicao: "7", titulo: "Self Control", duracao: "4:09" },
    { posicao: "8", titulo: "Good Guy", duracao: "1:06" },
    { posicao: "9", titulo: "Nights", duracao: "5:07" },
    { posicao: "10", titulo: "Solo (Reprise)", duracao: "1:18" },
    { posicao: "11", titulo: "Pretty Sweet", duracao: "2:38" },
    { posicao: "12", titulo: "Facebook Story", duracao: "1:08" },
    { posicao: "13", titulo: "Close To You", duracao: "1:25" },
    { posicao: "14", titulo: "White Ferrari", duracao: "4:08" },
    { posicao: "15", titulo: "Seigfried", duracao: "5:34" },
    { posicao: "16", titulo: "Godspeed", duracao: "2:57" },
    { posicao: "17", titulo: "Futura Free", duracao: "9:24" },
  ],
  1545493: [
    { posicao: "1", titulo: "Modern Slavery", duracao: "2:28" },
    { posicao: "2", titulo: "Black & Chinese", duracao: "2:52" },
    { posicao: "3", titulo: "Eye 2 Eye", duracao: "3:10" },
    { posicao: "4", titulo: "Motorcycle Patches", duracao: "3:11" },
    { posicao: "5", titulo: "Huncho Jack", duracao: "3:19" },
    { posicao: "6", titulo: "Saint", duracao: "2:20" },
    { posicao: "7", titulo: "Go", duracao: "2:36" },
    { posicao: "8", titulo: "Dubai Shit", duracao: "3:48" },
    { posicao: "9", titulo: "Saint Laurent Mask", duracao: "3:10" },
    { posicao: "10", titulo: "Moon Rock", duracao: "2:31" },
    { posicao: "11", titulo: "How U Feel", duracao: "3:25" },
    { posicao: "12", titulo: "Where U From", duracao: "4:11" },
    { posicao: "13", titulo: "Best Man", duracao: "4:26" },
  ],
  767810: [
    { posicao: "1", titulo: "Intro", duracao: "2:09" },
    { posicao: "2", titulo: "January 28th", duracao: "4:02" },
    { posicao: "3", titulo: "Wet Dreamz", duracao: "3:59" },
    { posicao: "4", titulo: "03' Adolescence", duracao: "4:24" },
    { posicao: "5", titulo: "A Tale Of 2 Citiez", duracao: "4:29" },
    { posicao: "6", titulo: "Fire Squad", duracao: "4:48" },
    { posicao: "7", titulo: "St. Tropez", duracao: "4:17" },
    { posicao: "8", titulo: "G.O.M.D.", duracao: "5:01" },
    { posicao: "9", titulo: "No Role Modelz", duracao: "4:52" },
    { posicao: "10", titulo: "Hello", duracao: "3:39" },
    { posicao: "11", titulo: "Apparently", duracao: "4:53" },
    { posicao: "12", titulo: "Love Yourz", duracao: "3:31" },
    { posicao: "13", titulo: "Note To Self", duracao: "14:35" },
  ],
  3933725: [
    { posicao: "1", titulo: "YouUgly", duracao: "4:43" },
    { posicao: "2", titulo: "Glory", duracao: "3:59" },
    { posicao: "3", titulo: "WRK", duracao: "3:14" },
    { posicao: "4", titulo: "Community", duracao: "4:25" },
    { posicao: "5", titulo: "Gz", duracao: "3:28" },
    { posicao: "6", titulo: "VCRs", duracao: "3:58" },
    { posicao: "7", titulo: "Sk8", duracao: "3:10" },
    { posicao: "8", titulo: "What We On", duracao: "3:58" },
    { posicao: "9", titulo: "Wholeheartedly", duracao: "3:45" },
    { posicao: "10", titulo: "No Boo", duracao: "3:35" },
    { posicao: "11", titulo: "And We Vibing (Interlude)", duracao: "0:41" },
    { posicao: "12", titulo: "On McAfee", duracao: "2:50" },
    { posicao: "13", titulo: "Of Blue", duracao: "6:36" },
    { posicao: "14", titulo: "K-Word", duracao: "5:11" },
    { posicao: "15", titulo: "For Keeps", duracao: "3:45" },
  ],
  6651: [
    { posicao: "A1", titulo: "Enter Sandman", duracao: "5:29" },
    { posicao: "A2", titulo: "Sad But True", duracao: "5:24" },
    { posicao: "A3", titulo: "Holier Than Thou", duracao: "3:47" },
    { posicao: "B1", titulo: "The Unforgiven", duracao: "6:26" },
    { posicao: "B2", titulo: "Wherever I May Roam", duracao: "6:42" },
    { posicao: "B3", titulo: "Don't Tread On Me", duracao: "3:59" },
    { posicao: "C1", titulo: "Through The Never", duracao: "4:01" },
    { posicao: "C2", titulo: "Nothing Else Matters", duracao: "6:29" },
    { posicao: "C3", titulo: "Of Wolf And Man", duracao: "4:16" },
    { posicao: "D1", titulo: "The God That Failed", duracao: "5:05" },
    { posicao: "D2", titulo: "My Friend Of Misery", duracao: "6:47" },
    { posicao: "D3", titulo: "The Struggle Within", duracao: "3:51" },
  ],
  1328530: [
    { posicao: "1-1", titulo: "Higher We Go (Intro)", duracao: "4:16" },
    { posicao: "1-2", titulo: "Superstars", duracao: "4:52" },
    { posicao: "1-3", titulo: "Narcos", duracao: "4:15" },
    { posicao: "1-4", titulo: "BBO (Bad B****** Only)", duracao: "4:11" },
    { posicao: "1-5", titulo: "Auto Pilot", duracao: "4:47" },
    { posicao: "1-6", titulo: "Walk It Talk It", duracao: "4:35" },
    { posicao: "1-7", titulo: "Emoji A Chain", duracao: "5:14" },
    { posicao: "1-8", titulo: "CC", duracao: "4:19" },
    { posicao: "1-9", titulo: "Stir Fry", duracao: "3:10" },
    { posicao: "1-10", titulo: "Too Much Jewelry", duracao: "4:05" },
    { posicao: "1-11", titulo: "Gang Gang", duracao: "3:01" },
    { posicao: "1-12", titulo: "White Sand", duracao: "3:22" },
    { posicao: "2-1", titulo: "Crown The Kings", duracao: "3:50" },
    { posicao: "2-2", titulo: "Flooded ", duracao: "4:29" },
    { posicao: "2-3", titulo: "Beast", duracao: "4:19" },
    { posicao: "2-4", titulo: "Open It Up", duracao: "4:05" },
    { posicao: "2-5", titulo: "Motorsport", duracao: "5:02" },
    { posicao: "2-6", titulo: "Movin' Too Fast", duracao: "4:23" },
    { posicao: "2-7", titulo: "Work Hard", duracao: "5:17" },
    { posicao: "2-8", titulo: "Notice Me", duracao: "3:53" },
    { posicao: "2-9", titulo: "Too Playa", duracao: "5:12" },
    { posicao: "2-10", titulo: "Made Men", duracao: "4:47" },
    { posicao: "2-11", titulo: "Top Down On Da Nawf", duracao: "4:55" },
    { posicao: "2-12", titulo: "Culture National Anthem (Outro)", duracao: "4:43" },
  ],
  2057692: [
    { posicao: "1", titulo: "Rockstar Made", duracao: "3:14" },
    { posicao: "2", titulo: "Go2DaMoon", duracao: "2:00" },
    { posicao: "3", titulo: "Stop Breathing", duracao: "3:39" },
    { posicao: "4", titulo: "Beno!", duracao: "2:33" },
    { posicao: "5", titulo: "JumpOutTheHouse", duracao: "1:33" },
    { posicao: "6", titulo: "M3tamorphosis", duracao: "5:12" },
    { posicao: "7", titulo: "Slay3r", duracao: "2:45" },
    { posicao: "8", titulo: "No Sl33p", duracao: "1:29" },
    { posicao: "9", titulo: "New Tank", duracao: "1:30" },
    { posicao: "10", titulo: "Teen X", duracao: "3:26" },
    { posicao: "11", titulo: "Meh", duracao: "1:59" },
    { posicao: "12", titulo: "Vamp Anthem", duracao: "2:04" },
    { posicao: "13", titulo: "New N3on", duracao: "1:56" },
    { posicao: "14", titulo: "Control", duracao: "3:18" },
    { posicao: "15", titulo: "Punk Monk", duracao: "3:50" },
    { posicao: "16", titulo: "On That Time", duracao: "1:42" },
    { posicao: "17", titulo: "King Vamp", duracao: "3:07" },
    { posicao: "18", titulo: "Place", duracao: "1:57" },
    { posicao: "19", titulo: "Sky", duracao: "3:13" },
    { posicao: "20", titulo: "Over", duracao: "2:46" },
    { posicao: "21", titulo: "ILoveUIHateU", duracao: "2:15" },
    { posicao: "22", titulo: "Die4Guy", duracao: "2:11" },
    { posicao: "23", titulo: "Not Playing", duracao: "2:10" },
    { posicao: "24", titulo: "F33l Lik3 Dyin", duracao: "3:24" },
  ],
  2929684: [
    { posicao: "1", titulo: "SOS", duracao: "1:57" },
    { posicao: "2", titulo: "Kill Bill", duracao: "2:33" },
    { posicao: "3", titulo: "Seek & Destroy", duracao: "3:23" },
    { posicao: "4", titulo: "Low", duracao: "3:01" },
    { posicao: "5", titulo: "Love Language", duracao: "3:03" },
    { posicao: "6", titulo: "Blind", duracao: "2:30" },
    { posicao: "7", titulo: "Used", duracao: "2:26" },
    { posicao: "8", titulo: "Snooze", duracao: "3:21" },
    { posicao: "9", titulo: "Notice Me", duracao: "2:40" },
    { posicao: "10", titulo: "Gone Girl", duracao: "4:04" },
    { posicao: "11", titulo: "Smoking On My Ex Pack", duracao: "1:23" },
    { posicao: "12", titulo: "Ghost In The Machine", duracao: "3:38" },
    { posicao: "13", titulo: "F2F", duracao: "3:05" },
    { posicao: "14", titulo: "Nobody Gets Me", duracao: "3:00" },
    { posicao: "15", titulo: "Conceited", duracao: "2:31" },
    { posicao: "16", titulo: "Special", duracao: "2:38" },
    { posicao: "17", titulo: "Too Late", duracao: "2:44" },
    { posicao: "18", titulo: "Far", duracao: "3:00" },
    { posicao: "19", titulo: "Shirt", duracao: "3:01" },
    { posicao: "20", titulo: "Open Arms", duracao: "3:59" },
    { posicao: "21", titulo: "I Hate U", duracao: "2:53" },
    { posicao: "22", titulo: "Good Days", duracao: "4:38" },
    { posicao: "23", titulo: "Forgiveless", duracao: "2:21" },
  ],
  3184197: [
    { posicao: "1", titulo: "Hyaena", duracao: "3:42" },
    { posicao: "2", titulo: "Thank God", duracao: "3:04" },
    { posicao: "3", titulo: "Modern Jam", duracao: "4:15" },
    { posicao: "4", titulo: "My Eyes", duracao: "4:11" },
    { posicao: "5", titulo: "God's Country", duracao: "2:07" },
    { posicao: "6", titulo: "Sirens", duracao: "3:24" },
    { posicao: "7", titulo: "Meltdown", duracao: "4:06" },
    { posicao: "8", titulo: "Fe!n", duracao: "3:11" },
    { posicao: "9", titulo: "Delresto (Echoes)", duracao: "4:34" },
    { posicao: "10", titulo: "I Know ?", duracao: "3:31" },
    { posicao: "11", titulo: "Topia Twins", duracao: "3:43" },
    { posicao: "12", titulo: "Circus Maximus", duracao: "4:18" },
    { posicao: "13", titulo: "Parasail", duracao: "2:34" },
    { posicao: "14", titulo: "Skitzo", duracao: "6:06" },
    { posicao: "15", titulo: "Lost Forever", duracao: "2:43" },
    { posicao: "16", titulo: "Looove", duracao: "3:46" },
    { posicao: "17", titulo: "K-Pop", duracao: "3:05" },
    { posicao: "18", titulo: "Telekinesis", duracao: "5:53" },
    { posicao: "19", titulo: "Til Further Notice", duracao: "5:14" },
  ],
  1694319: [
    { posicao: "1", titulo: "Just How It Is", duracao: "3:28" },
    { posicao: "2", titulo: "Sup Mate", duracao: "3:58" },
    { posicao: "3", titulo: "Ecstasy", duracao: "3:08" },
    { posicao: "4", titulo: "Hot", duracao: "3:13" },
    { posicao: "5", titulo: "Light It Up", duracao: "3:29" },
    { posicao: "6", titulo: "Surf", duracao: "3:04" },
    { posicao: "7", titulo: "Bad Bad Bad", duracao: "2:29" },
    { posicao: "8", titulo: "Lil Baby", duracao: "3:21" },
    { posicao: "9", titulo: "What's The Move", duracao: "4:11" },
    { posicao: "10", titulo: "I Bought Her", duracao: "3:21" },
    { posicao: "11", titulo: "Jumped Out The Window", duracao: "3:24" },
    { posicao: "12", titulo: "I'm Scared", duracao: "3:20" },
    { posicao: "13", titulo: "Cartier Gucci Scarf", duracao: "3:18" },
    { posicao: "14", titulo: "Big Tipper", duracao: "3:43" },
    { posicao: "15", titulo: "Pussy", duracao: "2:23" },
    { posicao: "16", titulo: "Circle Of Bosses", duracao: "2:59" },
    { posicao: "17", titulo: "Mannequin Challenge", duracao: "2:42" },
    { posicao: "18", titulo: "Boy Back", duracao: "3:22" },
    { posicao: "19", titulo: "The London", duracao: "3:20" },
  ],
  6983: [
    { posicao: "A1", titulo: "We Don't Care", duracao: "3:59" },
    { posicao: "A2", titulo: "Graduation Day", duracao: "1:21" },
    { posicao: "A3", titulo: "All Falls Down", duracao: "3:38" },
    { posicao: "A4", titulo: "Spaceship", duracao: "5:24" },
    { posicao: "A5", titulo: "Jesus Walks", duracao: "3:13" },
    { posicao: "B1", titulo: "Never Let Me Down", duracao: "5:24" },
    { posicao: "B2", titulo: "Get Em High", duracao: "4:49" },
    { posicao: "B3", titulo: "The New Workout Plan", duracao: "5:22" },
    { posicao: "B4", titulo: "Through The Wire", duracao: "3:41" },
    { posicao: "C1", titulo: "Slow Jamz", duracao: "5:15" },
    { posicao: "C2", titulo: "Breathe In Breathe Out", duracao: "4:06" },
    { posicao: "C3", titulo: "School Spirit", duracao: "3:02" },
    { posicao: "C4", titulo: "Two Words", duracao: "4:26" },
    { posicao: "D1", titulo: "Family Business", duracao: "4:38" },
    { posicao: "D2", titulo: "Last Call", duracao: "12:40" },
  ],
  124666: [
    { posicao: "1", titulo: "Red Intro", duracao: "1:52" },
    { posicao: "2", titulo: "How Many Mics", duracao: "4:29" },
    { posicao: "3", titulo: "Ready Or Not", duracao: "3:47" },
    { posicao: "4", titulo: "Zealots", duracao: "4:21" },
    { posicao: "5", titulo: "The Beast", duracao: "5:37" },
    { posicao: "6", titulo: "Fu-Gee-La", duracao: "4:20" },
    { posicao: "7", titulo: "Family Business", duracao: "5:44" },
    { posicao: "8", titulo: "Killing Me Softly", duracao: "4:59" },
    { posicao: "9", titulo: "The Score", duracao: "5:02" },
    { posicao: "10", titulo: "The Mask", duracao: "4:51" },
    { posicao: "11", titulo: "Cowboys", duracao: "5:24" },
    { posicao: "12", titulo: "No Woman, No Cry", duracao: "4:33" },
    { posicao: "13", titulo: "Manifest / Outro", duracao: "6:00" },
    { posicao: "14", titulo: "Fu-Gee-La (Refugee Camp Remix)", duracao: "4:24" },
    { posicao: "15", titulo: "Fu-Gee-La (Sly & Robbie Mix)", duracao: "5:27" },
    { posicao: "16", titulo: "Mista Mista", duracao: "2:43" },
  ],
  7087: [
    { posicao: "1", titulo: "Wake Up Mr. West", duracao: "0:41" },
    { posicao: "2", titulo: "Heard 'Em Say", duracao: "3:24" },
    { posicao: "3", titulo: "Touch The Sky", duracao: "3:56" },
    { posicao: "4", titulo: "Gold Digger", duracao: "3:27" },
    { posicao: "5", titulo: "Skit #1", duracao: "0:33" },
    { posicao: "6", titulo: "Drive Slow", duracao: "4:32" },
    { posicao: "7", titulo: "My Way Home", duracao: "1:43" },
    { posicao: "8", titulo: "Crack Music", duracao: "4:31" },
    { posicao: "9", titulo: "Roses", duracao: "4:05" },
    { posicao: "10", titulo: "Bring Me Down", duracao: "3:19" },
    { posicao: "11", titulo: "Addiction", duracao: "4:27" },
    { posicao: "12", titulo: "Skit #2", duracao: "0:31" },
    { posicao: "13", titulo: "Diamonds From Sierra Leone (Remix)", duracao: "3:53" },
    { posicao: "14", titulo: "We Major", duracao: "7:28" },
    { posicao: "15", titulo: "Skit #3", duracao: "0:24" },
    { posicao: "16", titulo: "Hey Mama", duracao: "5:05" },
    { posicao: "17", titulo: "Celebration", duracao: "3:18" },
    { posicao: "18", titulo: "Skit #4", duracao: "1:19" },
    { posicao: "19", titulo: "Gone", duracao: "5:33" },
    { posicao: "20", titulo: "Diamonds From Sierra Leone", duracao: "3:58" },
    { posicao: "21", titulo: "Late", duracao: "3:50" },
  ],
  3905515: [
    { posicao: "1", titulo: "The Birds Don't Sing", duracao: "4:00" },
    { posicao: "2", titulo: "Chains & Whips", duracao: "4:03" },
    { posicao: "3", titulo: "P.O.V.", duracao: "4:18" },
    { posicao: "4", titulo: "Ace Trumpets", duracao: "2:34" },
    { posicao: "5", titulo: "All Things Considered", duracao: "3:09" },
    { posicao: "6", titulo: "MTBTTF", duracao: "2:36" },
    { posicao: "7", titulo: "E.B.I.T.D.A.", duracao: "1:59" },
    { posicao: "8", titulo: "F.I.C.O.", duracao: "3:21" },
    { posicao: "9", titulo: "Inglorious Bastards", duracao: "2:33" },
    { posicao: "10", titulo: "So Far Ahead", duracao: "3:22" },
    { posicao: "11", titulo: "Let God Sort Em Out / Chandeliers", duracao: "2:32" },
    { posicao: "12", titulo: "By The Grace Of God", duracao: "3:06" },
  ],
  21491: [
    { posicao: "A1", titulo: "Airbag", duracao: "4:44" },
    { posicao: "A2", titulo: "Paranoid Android", duracao: "6:23" },
    { posicao: "A3", titulo: "Subterranean Homesick Alien", duracao: "4:27" },
    { posicao: "B4", titulo: "Exit Music (For A Film)", duracao: "4:24" },
    { posicao: "B5", titulo: "Let Down", duracao: "4:59" },
    { posicao: "B6", titulo: "Karma Police", duracao: "4:21" },
    { posicao: "C7", titulo: "Fitter Happier", duracao: "1:57" },
    { posicao: "C8", titulo: "Electioneering", duracao: "3:50" },
    { posicao: "C9", titulo: "Climbing Up The Walls", duracao: "4:45" },
    { posicao: "C10", titulo: "No Surprises", duracao: "3:48" },
    { posicao: "D11", titulo: "Lucky", duracao: "4:19" },
    { posicao: "D12", titulo: "The Tourist", duracao: "5:25" },
  ],
  26647: [
    { posicao: "A1", titulo: "One More Time", duracao: "5:20" },
    { posicao: "A2", titulo: "Aerodynamic", duracao: "3:27" },
    { posicao: "A3", titulo: "Digital Love", duracao: "4:58" },
    { posicao: "B1", titulo: "Harder, Better, Faster, Stronger", duracao: "3:44" },
    { posicao: "B2", titulo: "Crescendolls", duracao: "3:28" },
    { posicao: "B3", titulo: "Nightvision", duracao: "1:44" },
    { posicao: "B4", titulo: "Superheroes", duracao: "3:57" },
    { posicao: "C1", titulo: "High Life", duracao: "3:19" },
    { posicao: "C2", titulo: "Something About Us", duracao: "3:51" },
    { posicao: "C3", titulo: "Voyager", duracao: "3:44" },
    { posicao: "C4", titulo: "Veridis Quo", duracao: "5:44" },
    { posicao: "D1", titulo: "Short Circuit", duracao: "3:24" },
    { posicao: "D2", titulo: "Face To Face", duracao: "3:58" },
    { posicao: "D3", titulo: "Too Long", duracao: "10:00" },
  ],
  556257: [
    { posicao: "A1", titulo: "Give Life Back To Music", duracao: "4:35" },
    { posicao: "A2", titulo: "The Game Of Love", duracao: "5:22" },
    { posicao: "A3", titulo: "Giorgio By Moroder", duracao: "9:04" },
    { posicao: "B1", titulo: "Within", duracao: "3:48" },
    { posicao: "B2", titulo: "Instant Crush", duracao: "5:37" },
    { posicao: "B3", titulo: "Lose Yourself To Dance", duracao: "5:53" },
    { posicao: "C1", titulo: "Touch", duracao: "8:18" },
    { posicao: "C2", titulo: "Get Lucky", duracao: "6:09" },
    { posicao: "C3", titulo: "Beyond", duracao: "4:50" },
    { posicao: "D1", titulo: "Motherboard", duracao: "5:41" },
    { posicao: "D2", titulo: "Fragments Of Time", duracao: "4:39" },
    { posicao: "D3", titulo: "Doin' It Right", duracao: "4:11" },
    { posicao: "D4", titulo: "Contact", duracao: "6:23" },
  ],
  1681919: [
    { posicao: "A1", titulo: "One More Year", duracao: "5:23" },
    { posicao: "A2", titulo: "Instant Destiny", duracao: "3:12" },
    { posicao: "A3", titulo: "Borderline", duracao: "3:56" },
    { posicao: "B1", titulo: "Posthumous Forgiveness", duracao: "6:02" },
    { posicao: "B2", titulo: "Breathe Deeper", duracao: "6:08" },
    { posicao: "B3", titulo: "Tomorrow's Dust", duracao: "5:25" },
    { posicao: "C1", titulo: "On Track", duracao: "4:59" },
    { posicao: "C2", titulo: "Lost In Yesterday", duracao: "4:07" },
    { posicao: "C3", titulo: "Is It True", duracao: "3:56" },
    { posicao: "D1", titulo: "It Might Be Time", duracao: "4:32" },
    { posicao: "D2", titulo: "Glimmer", duracao: "2:06" },
    { posicao: "D3", titulo: "One More Hour", duracao: "7:06" },
  ],
  69774: [
    { posicao: "1", titulo: "Brianstorm", duracao: "2:50" },
    { posicao: "2", titulo: "Teddy Picker", duracao: "2:43" },
    { posicao: "3", titulo: "D Is For Dangerous", duracao: "2:16" },
    { posicao: "4", titulo: "Balaclava", duracao: "2:49" },
    { posicao: "5", titulo: "Fluorescent Adolescent", duracao: "2:57" },
    { posicao: "6", titulo: "Only Ones Who Know", duracao: "3:02" },
    { posicao: "7", titulo: "Do Me A Favour", duracao: "3:27" },
    { posicao: "8", titulo: "This House Is A Circus", duracao: "3:09" },
    { posicao: "9", titulo: "If You Were There, Beware", duracao: "4:34" },
    { posicao: "10", titulo: "The Bad Thing", duracao: "2:23" },
    { posicao: "11", titulo: "Old Yellow Bricks", duracao: "3:11" },
    { posicao: "12", titulo: "505", duracao: "4:13" },
  ],
  1591877: [
    { posicao: "1", titulo: "Igor's Theme", duracao: "3:20" },
    { posicao: "2", titulo: "Earfquake", duracao: "3:10" },
    { posicao: "3", titulo: "I Think", duracao: "3:32" },
    { posicao: "4", titulo: "Exactly What You Run From You End Up Chasing", duracao: "0:14" },
    { posicao: "5", titulo: "Running Out Of Time", duracao: "2:57" },
    { posicao: "6", titulo: "New Magic Wand", duracao: "3:15" },
    { posicao: "7", titulo: "A Boy Is A Gun", duracao: "3:30" },
    { posicao: "8", titulo: "Puppet", duracao: "2:59" },
    { posicao: "9", titulo: "What's Good", duracao: "3:25" },
    { posicao: "10", titulo: "Gone, Gone / Thank You", duracao: "6:15" },
    { posicao: "11", titulo: "I Don't Love You Anymore", duracao: "2:41" },
    { posicao: "12", titulo: "Are We Still Friends?", duracao: "4:25" },
  ],
  54526: [
    { posicao: "A1", titulo: "Panis Et Circensis", duracao: "3:38" },
    { posicao: "A2", titulo: "A Minha Menina", duracao: "4:42" },
    { posicao: "A3", titulo: "O Relógio", duracao: "3:30" },
    { posicao: "A4", titulo: "Adeus Maria Fulô", duracao: "3:04" },
    { posicao: "A5", titulo: "Baby", duracao: "3:00" },
    { posicao: "A6", titulo: "Senhor F", duracao: "2:33" },
    { posicao: "B1", titulo: "Bat Macumba", duracao: "3:10" },
    { posicao: "B2", titulo: "Le Premier Bonheur Du Jour", duracao: "3:36" },
    { posicao: "B3", titulo: "Trem Fantasma", duracao: "3:16" },
    { posicao: "B4", titulo: "Tempo No Tempo (Once Was A Time I Thought)", duracao: "1:47" },
    { posicao: "B5", titulo: "Ave Gengis Khan", duracao: "3:47" },
  ],
  17217: [
    { posicao: "A1", titulo: "Wouldn't It Be Nice", duracao: "2:22" },
    { posicao: "A2", titulo: "You Still Believe In Me", duracao: "2:33" },
    { posicao: "A3", titulo: "That's Not Me", duracao: "2:27" },
    { posicao: "A4", titulo: "Don't Talk (Put Your Head On My Shoulder)", duracao: "2:52" },
    { posicao: "A5", titulo: "I'm Waiting For The Day", duracao: "3:01" },
    { posicao: "A6", titulo: "Let's Go Away For Awhile", duracao: "2:18" },
    { posicao: "A7", titulo: "Sloop John B", duracao: "2:57" },
    { posicao: "B1", titulo: "God Only Knows", duracao: "2:46" },
    { posicao: "B2", titulo: "I Know There's An Answer", duracao: "3:10" },
    { posicao: "B3", titulo: "Here Today", duracao: "2:38" },
    { posicao: "B4", titulo: "I Just Wasn't Made For These Times", duracao: "3:21" },
    { posicao: "B5", titulo: "Pet Sounds", duracao: "2:20" },
    { posicao: "B6", titulo: "Caroline, No", duracao: "2:16" },
  ],
  24497: [
    { posicao: "A1", titulo: "Foxy Lady", duracao: "3:11" },
    { posicao: "A2", titulo: "Manic Depression", duracao: "3:30" },
    { posicao: "A3", titulo: "Red House", duracao: "3:40" },
    { posicao: "A4", titulo: "Can You See Me", duracao: "2:23" },
    { posicao: "A5", titulo: "Love Or Confusion", duracao: "3:03" },
    { posicao: "A6", titulo: "I Don't Live Today", duracao: "3:44" },
    { posicao: "B1", titulo: "May This Be Love", duracao: "2:55" },
    { posicao: "B2", titulo: "Fire", duracao: "2:29" },
    { posicao: "B3", titulo: "3rd Stone From The Sun", duracao: "6:28" },
    { posicao: "B4", titulo: "Remember", duracao: "2:41" },
    { posicao: "B5", titulo: "Are You Experienced", duracao: "2:53" },
  ],
  16158: [
    { posicao: "A1", titulo: "Maggot Brain", duracao: "10:10" },
    { posicao: "A2", titulo: "Can You Get To That", duracao: "2:45" },
    { posicao: "A3", titulo: "Hit It And Quit It", duracao: "3:44" },
    { posicao: "A4", titulo: "You And Your Folks, Me And My Folks", duracao: "3:29" },
    { posicao: "B1", titulo: "Super Stupid", duracao: "3:53" },
    { posicao: "B2", titulo: "Back In Our Minds", duracao: "2:35" },
    { posicao: "B3", titulo: "Wars Of Armageddon", duracao: "9:28" },
  ],
  87440: [
    { posicao: "A1", titulo: "Love's In Need Of Love Today", duracao: "7:05" },
    { posicao: "A2", titulo: "Have A Talk With God", duracao: "2:42" },
    { posicao: "A3", titulo: "Village Ghetto Land", duracao: "3:25" },
    { posicao: "A4", titulo: "Contusion", duracao: "3:45" },
    { posicao: "A5", titulo: "Sir Duke", duracao: "3:52" },
    { posicao: "B1", titulo: "I Wish", duracao: "4:12" },
    { posicao: "B2", titulo: "Knocks Me Off My Feet", duracao: "3:35" },
    { posicao: "B3", titulo: "Pastime Paradise", duracao: "3:20" },
    { posicao: "B4", titulo: "Summer Soft", duracao: "4:16" },
    { posicao: "B5", titulo: "Ordinary Pain", duracao: "6:22" },
    { posicao: "C1", titulo: "Isn't She Lovely", duracao: "6:33" },
    { posicao: "C2", titulo: "Joy Inside My Tears", duracao: "6:29" },
    { posicao: "C3", titulo: "Black Man", duracao: "8:29" },
    { posicao: "D1", titulo: "Ngiculela - Es Una Historia - I Am Singing", duracao: "3:48" },
    { posicao: "D2", titulo: "If It's Magic", duracao: "3:11" },
    { posicao: "D3", titulo: "As", duracao: "7:07" },
    { posicao: "D4", titulo: "Another Star", duracao: "8:19" },
    { posicao: "E1", titulo: "Saturn", duracao: "4:54" },
    { posicao: "E2", titulo: "Ebony Eyes", duracao: "4:10" },
    { posicao: "F1", titulo: "All Day Sucker", duracao: "5:06" },
    { posicao: "F2", titulo: "Easy Goin' Evening (My Mama's Call)", duracao: "3:58" },
  ],
  112296: [
    { posicao: "A1", titulo: "Ponta De Lança Africano (Umbabarauma)", duracao: "3:58" },
    { posicao: "A2", titulo: "Hermes Trismegisto Escreveu", duracao: "3:04" },
    { posicao: "A3", titulo: "O Filósofo", duracao: "3:30" },
    { posicao: "A4", titulo: "Meus Filhos, Meu Tesouro", duracao: "3:53" },
    { posicao: "A5", titulo: "O Plebeu", duracao: "3:18" },
    { posicao: "A6", titulo: "Taj Mahal", duracao: "3:10" },
    { posicao: "B1", titulo: "Xica Da Silva", duracao: "4:00" },
    { posicao: "B2", titulo: "A História De Jorge", duracao: "3:53" },
    { posicao: "B3", titulo: "Camisa 10 Da Gávea", duracao: "4:18" },
    { posicao: "B4", titulo: "Cavaleiro Do Cavalo Imaculado", duracao: "4:43" },
    { posicao: "B5", titulo: "África Brasil (Zumbi)", duracao: "3:48" },
  ],
  16245: [
    { posicao: "A1", titulo: "Let's Go Crazy", duracao: "4:39" },
    { posicao: "A2", titulo: "Take Me With U", duracao: "3:54" },
    { posicao: "A3", titulo: "The Beautiful Ones", duracao: "5:15" },
    { posicao: "A4", titulo: "Computer Blue", duracao: "3:59" },
    { posicao: "A5", titulo: "Darling Nikki", duracao: "4:15" },
    { posicao: "B1", titulo: "When Doves Cry", duracao: "5:52" },
    { posicao: "B2", titulo: "I Would Die 4 U", duracao: "2:51" },
    { posicao: "B3", titulo: "Baby I'm A Star", duracao: "4:20" },
    { posicao: "B4", titulo: "Purple Rain", duracao: "8:45" },
  ],
  30296: [
    { posicao: "A1", titulo: "Countdown To Armageddon", duracao: "1:41" },
    { posicao: "A2", titulo: "Bring The Noise", duracao: "3:47" },
    { posicao: "A3", titulo: "Don't Believe The Hype", duracao: "5:20" },
    { posicao: "A4", titulo: "Cold Lampin With Flavor", duracao: "4:13" },
    { posicao: "A5", titulo: "Terminator X To The Edge Of Panic", duracao: "4:30" },
    { posicao: "A6", titulo: "Mind Terrorist", duracao: "1:18" },
    { posicao: "A7", titulo: "Louder Than A Bomb", duracao: "3:37" },
    { posicao: "A8", titulo: "Caught, Can We Get A Witness?", duracao: "5:03" },
    { posicao: "B1", titulo: "Show 'Em Whatcha Got", duracao: "1:57" },
    { posicao: "B2", titulo: "She Watch Channel Zero?!", duracao: "3:50" },
    { posicao: "B3", titulo: "Night Of The Living Baseheads", duracao: "3:16" },
    { posicao: "B4", titulo: "Black Steel In The Hour Of Chaos", duracao: "6:25" },
    { posicao: "B5", titulo: "Security Of The First World", duracao: "1:22" },
    { posicao: "B6", titulo: "Rebel Without A Pause", duracao: "5:05" },
    { posicao: "B7", titulo: "Prophets Of Rage", duracao: "3:15" },
    { posicao: "B8", titulo: "Party For Your Right To Fight", duracao: "3:27" },
  ],
  43936: [
    { posicao: "A1", titulo: "Smooth Operator", duracao: "4:58" },
    { posicao: "A2", titulo: "Your Love Is King", duracao: "3:40" },
    { posicao: "A3", titulo: "Hang On To Your Love", duracao: "5:54" },
    { posicao: "A4", titulo: "Frankie's First Affair", duracao: "4:38" },
    { posicao: "A5", titulo: "When Am I Going To Make A Living", duracao: "3:25" },
    { posicao: "B1", titulo: "Cherry Pie", duracao: "6:20" },
    { posicao: "B2", titulo: "Sally", duracao: "5:20" },
    { posicao: "B3", titulo: "I Will Be Your Friend", duracao: "4:43" },
    { posicao: "B4", titulo: "Why Can't We Live Together", duracao: "5:27" },
  ],
  20148: [
    { posicao: "A1", titulo: "The Genesis", duracao: "1:45" },
    { posicao: "A2", titulo: "N.Y. State Of Mind", duracao: "4:52" },
    { posicao: "A3", titulo: "Life's A Bitch", duracao: "3:29" },
    { posicao: "A4", titulo: "The World Is Yours", duracao: "4:50" },
    { posicao: "A5", titulo: "Halftime", duracao: "4:21" },
    { posicao: "B1", titulo: "Memory Lane (Sittin' In Da Park)", duracao: "4:06" },
    { posicao: "B2", titulo: "One Love", duracao: "5:24" },
    { posicao: "B3", titulo: "One Time 4 Your Mind", duracao: "3:17" },
    { posicao: "B4", titulo: "Represent", duracao: "4:13" },
    { posicao: "B5", titulo: "It Ain't Hard To Tell", duracao: "3:22" },
  ],
  23683: [
    { posicao: "A1", titulo: "Angel", duracao: "6:18" },
    { posicao: "A2", titulo: "Risingson", duracao: "4:58" },
    { posicao: "A3", titulo: "Teardrop", duracao: "5:29" },
    { posicao: "B1", titulo: "Inertia Creeps", duracao: "5:56" },
    { posicao: "B2", titulo: "Exchange", duracao: "4:11" },
    { posicao: "B3", titulo: "Dissolved Girl", duracao: "6:07" },
    { posicao: "C1", titulo: "Man Next Door", duracao: "5:55" },
    { posicao: "C2", titulo: "Black Milk", duracao: "6:20" },
    { posicao: "C3", titulo: "Mezzanine", duracao: "5:54" },
    { posicao: "D1", titulo: "Group Four", duracao: "8:13" },
    { posicao: "D2", titulo: "(Exchange)", duracao: "4:08" },
  ],
  12347: [
    { posicao: "1", titulo: "Is This It", duracao: "2:35" },
    { posicao: "2", titulo: "The Modern Age", duracao: "3:32" },
    { posicao: "3", titulo: "Soma", duracao: "2:37" },
    { posicao: "4", titulo: "Barely Legal", duracao: "3:58" },
    { posicao: "5", titulo: "Someday", duracao: "3:07" },
    { posicao: "6", titulo: "Alone, Together", duracao: "3:12" },
    { posicao: "7", titulo: "Last Nite", duracao: "3:17" },
    { posicao: "8", titulo: "Hard To Explain", duracao: "3:47" },
    { posicao: "9", titulo: "New York City Cops", duracao: "3:36" },
    { posicao: "10", titulo: "Trying Your Luck", duracao: "3:27" },
    { posicao: "11", titulo: "Take It Or Leave It", duracao: "3:16" },
  ],
  51256: [
    { posicao: "1", titulo: "Rehab", duracao: "3:34" },
    { posicao: "2", titulo: "You Know I'm No Good", duracao: "4:17" },
    { posicao: "3", titulo: "Me And Mr Jones", duracao: "2:33" },
    { posicao: "4", titulo: "Just Friends", duracao: "3:13" },
    { posicao: "5", titulo: "Back To Black", duracao: "4:01" },
    { posicao: "6", titulo: "Love Is A Losing Game", duracao: "2:35" },
    { posicao: "7", titulo: "Tears Dry On Their Own", duracao: "3:06" },
    { posicao: "8", titulo: "Wake Up Alone", duracao: "3:42" },
    { posicao: "9", titulo: "Some Unholy War", duracao: "2:22" },
    { posicao: "10", titulo: "He Can Only Hold Her", duracao: "2:46" },
    { posicao: "11", titulo: "Addicted", duracao: "2:45" },
  ],
  191288: [
    { posicao: "1", titulo: "In My Dreams (Cudder Anthem)", duracao: "3:19" },
    { posicao: "2", titulo: "Soundtrack 2 My Life", duracao: "3:55" },
    { posicao: "3", titulo: "Simple As...", duracao: "2:31" },
    { posicao: "4", titulo: "Mr. Solo Dolo (Nightmare)", duracao: "4:26" },
    { posicao: "5", titulo: "Heart Of A Lion (Kid Cudi Theme Music)", duracao: "4:21" },
    { posicao: "6", titulo: "My World", duracao: "4:03" },
    { posicao: "7", titulo: "Day 'n' Nite (Nightmare)", duracao: "3:41" },
    { posicao: "8", titulo: "Sky Might Fall", duracao: "3:41" },
    { posicao: "9", titulo: "Enter Galactic (Love Connection Part I)", duracao: "4:20" },
    { posicao: "10", titulo: "Alive (Nightmare)", duracao: "4:06" },
    { posicao: "11", titulo: "CuDi Zone", duracao: "4:19" },
    { posicao: "12", titulo: "Make Her Say", duracao: "3:36" },
    { posicao: "13", titulo: "Pursuit Of Happiness (Nightmare)", duracao: "4:55" },
    { posicao: "14", titulo: "Hyyerr", duracao: "3:32" },
    { posicao: "15", titulo: "Up Up & Away (The Wake & Bake Song)", duracao: "3:47" },
  ],
};
